#!/usr/bin/env python3
"""Assemble one build brief: house laws and builder rules, the unit spec preamble and the sub unit's OWN section, and every real file the sub unit's
own spec section names (big files sliced verbatim): every one is shown, or named with a NOT SHOWN marker, never omitted.
usage (repo root): build_brief.py <unit> <sub> <spec.md> <out.md>
Prints the owned paths, one per line, so the caller can refuse two lanes on one file. Exit 2 if the section is absent,
if the files cannot all be named within the budget, or if BROTHER_BRIEF_SCREEN is not on or off. BROTHER_BRIEF_SCREEN=on
adds THE GRADER'S SCREEN, generated by grade_build.screen_rules; unset or off (the default) the brief is today's."""
import datetime, json, os, re, sys
# The slicer beside THIS file first (a stamp ships both together, and a tree run must test the tree's slicer, not
# the deployed one: on 2026-09-24 a fix proven "on the real brief" had silently used the old slicer), then the stamp.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))   # the copy beside this file, and only that one
from slicer import slice_source
import grade_build as _G
import land_apply as _LA   # THE HOSTILE INPUT CONTRACT: generated from the landing fuzz itself (build quality, 2026-10-05)
from brief_check import SPEC_PATH, labelled_paths
# THE LESSONS STORE COMES FROM THE CODE ROOT (2026-09-29), exactly as model_call reaches the dispatch pool: never a path
# counted up from __file__. The deployed copy runs from ~/.claude/bin, a symlink to a deploy tree's scripts/loop that
# holds no plugin/ tree, so three parents up (resolved or not) never held the runtime and every live brief read
# LESSONS NO-DATA; the runtime sits under the code root (<bin>/candidate in a proof). A STATIC import, so the deploy
# freeze traces it; a refused code root or a missing module leaves it None and lesson_block answers NO-DATA.
import model_router as _R
try:
    _CODE_ROOT, _NO_CODE_ROOT = _R.code_root(), ""
except _R.Refused as exc:
    _CODE_ROOT, _NO_CODE_ROOT = None, str(exc)
_DREAM_EPISODE_PATH = (os.path.join(_CODE_ROOT, "plugin", "runtime", "brother", "core", "dream_episode.py")
                       if _CODE_ROOT else "any code root (%s)" % _NO_CODE_ROOT)
if _CODE_ROOT and _CODE_ROOT not in sys.path:
    sys.path.insert(0, _CODE_ROOT)
try:
    if not _CODE_ROOT:
        raise ImportError(_NO_CODE_ROOT)
    from plugin.runtime.brother.core import dream_episode as _DE
    _DE_WHY = ""
except ImportError as exc:
    _DE, _DE_WHY = None, str(exc)
unit, sub, spec_path, out = sys.argv[1:5]
# THE HEAD IS VERSIONED (2026-09-24, owner: "improve and enforce clear briefs per units and from Epic"): until this
# commit every worker's hard rules were read from a one off evidence prompt outside every repository and truncated at a
# text marker, so nothing reviewed, deployed or tested them. It ships beside this file in every stamp; a missing head is
# a refusal, never a brief without rules.
try:
    with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "brief_head.md"), encoding="utf-8") as f:
        head = f.read()
except OSError as exc:
    sys.stderr.write("brief_head.md missing beside build_brief.py: %s\n" % exc); sys.exit(2)
with open(spec_path, encoding="utf-8") as f:
    spec = f.read()
m = re.search(r"^#{2,4} %s\b.*?(?=^#{2,4} |\Z)" % re.escape(sub), spec, flags=re.M | re.S)
if not m:
    sys.exit(2)
section = m.group(0)
def paths_in(text):
    """Backticked file paths, plus the modules named by any dotted done_check.

    A DONE CHECK NAMES THE MODULE, and until 2026-09-21 nothing read it. Measured that day over four live
    briefs: two carried 49 and 969 bytes of real source, which is none, against a budget of 196500 that was
    nowhere near spent. The cause was not the budget at all. D9.d's whole section reads "Exact files: same two
    NEW files", naming its files by pointing at a sibling section rather than by naming them, so the path regex
    found nothing and the builder was handed ZERO source while still being told its tests must fail without its
    code. That lane could not have succeeded, and it burned its rounds proving it.

    Its done check, however, says it plainly:
      python3 -B -m unittest plugin.runtime.brother.core.test_dream_grade.TestComparator
    which names a test module, and by this estate's own convention the module under test sits beside it. Both
    are recovered here. A dotted name that resolves to no file on disk is dropped rather than guessed at."""
    out = []
    paths_in.neighbours = []      # the suites added by convention below, so the budget can rank them after the named files
    # A LABEL INSIDE THE BACKTICK USED TO BREAK EVERY MATCH. Measured 2026-09-21 on L0.1, whose section is 2981
    # bytes and named SIX real paths, every one of them written as `NEW: docs/plan/L0-WAIVERS.json` or
    # `existing: scripts/l0_gate.py`. The old pattern anchored the path to the backticks, so the "NEW: " prefix
    # made it match nothing and the builder was handed zero source. Third distinct shape of the same starvation,
    # after a section that names files by pointing at a sibling and a section that names only a done check.
    for q in SPEC_PATH.findall(text):   # brief_check.SPEC_PATH, the one reader; data files (.jsonl) are not source to show
        if q not in out and not q.startswith("docs/plan/specs/") and not q.endswith(".jsonl"):
            out.append(q)
    # A DONE CHECK THAT NAMES ITS DEPENDENTS (2026-09-30, L5a spec round 3): the landing gate runs only the section's one
    # command, so a section puts the suites its change must keep green after its own test module in that command. Those
    # suites are regression guards, not the files the builder edits: ranked with the named files, with their modules and
    # imports, they took the budget and sliced out the functions L5a-8c owns (run_wave, _record_choice). Every module
    # after the first of a `-m unittest` command is a neighbour: shown when the budget allows, never followed further.
    # A path the section also names in backticks stays a named file (the loop above already put it first).
    commands = [m.group(1).split() for m in re.finditer(r"-m unittest ([\w. ]+)", text)]
    dependents = {t for c in commands for t in c[1:]} - {c[0] for c in commands if c}
    for dotted_name in re.findall(r"\b((?:[A-Za-z_][A-Za-z0-9_]*\.){2,}[A-Za-z_][A-Za-z0-9_]*)", text):
        parts = dotted_name.split(".")
        for cut in range(len(parts), 1, -1):          # trim a trailing class or method until a file appears
            rel = os.path.join(*parts[:cut]) + ".py"
            if not os.path.isfile(rel):
                continue
            if dotted_name in dependents:
                if rel not in out:
                    out.append(rel); paths_in.neighbours.append(rel)
                break
            if rel not in out:
                out.append(rel)
            base = os.path.basename(rel)
            if base.startswith("test_"):              # the module under test sits beside its test, by convention
                sib = os.path.join(os.path.dirname(rel), base[len("test_"):])
                if os.path.isfile(sib) and sib not in out:
                    out.append(sib)
            break
    named_tests = [r for r in out if os.path.basename(r).startswith("test_") and r.endswith(".py") and os.path.isfile(r)
                   and r not in paths_in.neighbours]
    # THE MODULE'S EXISTING SUITES RIDE ALONG (2026-09-24: 963 grader refusals on record read "suite not green with the
    # code", the night's biggest class; the worker was shown the module and never the tests beside it that its edit
    # must keep green). Every real module named gets its test_<module>*.py neighbours, every test gets its module.
    for rel in list(out):
        if not os.path.isfile(rel) or not rel.endswith(".py") or rel in paths_in.neighbours: continue
        d, base = os.path.dirname(rel), os.path.basename(rel)
        sibs = ([os.path.join(d, base[len("test_"):])] if base.startswith("test_") else
                sorted(os.path.join(d, n) for n in os.listdir(d or ".") if n.startswith("test_" + base[:-3]) and n.endswith(".py")))
        for s in sibs:
            if os.path.isfile(s) and s not in out:
                out.append(s)
                # only a SUITE is a neighbour; the module a named test brings is the thing under test and ranks with
                # the named files (R4.2, 2026-09-24: jev_seam.py came in as test_jev_seam.py's sibling, was ranked
                # second, and got a 2 byte share while the sub unit exists to test it)
                if os.path.basename(s).startswith("test_"): paths_in.neighbours.append(s)
    # A TEST'S IMPORTS RIDE ALONG (2026-09-24 12:5x, run 2: D3.7 and D1.8, both test only sub units, burned eleven
    # builds at "suite not green with the code" and every UNKNOWNS line named the same thing, the module under
    # test not shown. The rule above finds the module BESIDE the test, and test_dream_seams.py tests
    # scripts/jev_seam.py; the brief carried the test file and ZERO modules, the workers guessed every shape, and
    # the real modules refused every guess: an attempts ledger read as corrupt, a status name that does not exist.)
    # Each import of a named test file that resolves to a real file in the tree is shown, tried as a package path,
    # beside the test, and under scripts/, which is where this estate's plugin tests insert into sys.path. Read
    # only, one level, and a name that resolves to no file is dropped, never guessed. ONLY the tests the section
    # itself names are followed, never the neighbour suites added above: following those too handed D1.8 thirty
    # five files, and the budget split that wide left nineteen of them NOT SHOWN, the starvation this exists to end.
    for rel in named_tests:
        try:
            with open(rel, encoding="utf-8") as fh:
                text = fh.read()
        except OSError:   # sbe: allow-silent a file that cannot be read is left out of the brief, and brief_check B1 NAMED SHOWN refuses the brief by name
            continue
        for m in re.finditer(r"^\s*(?:from\s+([A-Za-z_][\w.]*)\s+import\b|import\s+([A-Za-z_][\w.]*(?:\s*,\s*[A-Za-z_][\w.]*)*))", text, re.M):
            names = [m.group(1)] if m.group(1) else [n.strip() for n in m.group(2).split(",")]
            for name in names:
                parts = name.split(".")
                for cut in range(len(parts), 0, -1):
                    hit = next((c for c in (os.path.normpath(os.path.join(pre, *parts[:cut]) + ".py")
                                            for pre in ("", os.path.dirname(rel), "scripts"))
                                if os.path.isfile(c) and c != rel), None)
                    if hit:
                        if hit not in out: out.append(hit)
                        break
    return out


paths = paths_in(section)
neighbours = set(paths_in.neighbours)
if not [q for q in paths if os.path.isfile(q)]:
    # A SECTION THAT NAMES NOTHING falls back to its whole unit's spec rather than dispatching a builder blind.
    # Zero real source is the one input that makes hard rule 4 impossible to satisfy, so it is worth a wider net.
    for q in paths_in(spec):
        if q not in paths:
            paths.append(q)
    neighbours |= set(paths_in.neighbours)
existing = [p for p in paths if os.path.isfile(p)]
new = [p for p in paths if not os.path.isfile(p)]


def stale_claims(section_text, existing_paths):
    """Where the SPECIFICATION and the TREE disagree, stated as corrections the builder reads FIRST.

    THIS IS THE FIX FOR THE LARGEST MEASURED CAUSE OF A DEAD LANE. On 2026-09-21 a diagnostician round over 13
    stuck sub units returned 9 proven facts, and the same shape kept coming back: the spec asserts something is
    NEW and it already exists. Three of the nine verbatim: "scripts/loop_bridge.py already defines run_node, so
    D1.5's spec's claim that run_node is NEW is false"; "test_dream_world.py already exists with the TestSchema
    tests"; "dream_grade.py already contains the D9.d _classify implementation".

    The brief already listed which files exist, but the SPEC TEXT inside the same brief still said "create it".
    A builder handed two contradictory instructions spends its rounds trying to satisfy both, then exhausts, and
    the loop calls it a missing fact. It was never missing: it was present and contradicted.

    The deterministic scorer deliberately does NOT judge this case (its own comment: "NEW and present is NOT
    judged: an earlier sub unit of the same unit legitimately creates it"), and that exemption is right, because
    a sibling sub unit creating the file first is normal and healthy. The exemption is about whether the SPEC is
    WRONG; this function is about what the BUILDER IS TOLD. Both can be true: the spec stays valid, and the
    builder is told the file is already there.

    Fails toward saying nothing: anything unreadable is skipped, never guessed at, because a false correction
    would be worse than the silence it replaces. The occurrences of a path come from brief_check.labelled_paths,
    the one reader of every NEW spelling, inside the backticks (`NEW: p`, `p (NEW)`) or outside."""
    out = []
    for path in existing_paths:
        # the token's own label, or the words within about 120 characters of it, which is where a NEW marker sits
        for p, label, start, end in labelled_paths(section_text):
            if p != path:
                continue
            around = section_text[max(0, start - 120):end + 120]
            if label == "NEW" or re.search(r"\bNEW\b", around):
                out.append("%s is called NEW by the specification and ALREADY EXISTS on disk. Read it below, "
                           "extend it, and never recreate it." % path)
                break
    # symbols the section introduces as new that are already defined somewhere in the tree
    for sym in dict.fromkeys(re.findall(r"\b(?:new|add|create|introduce)s?\s+`([A-Za-z_][A-Za-z0-9_]*)\(`",
                                        section_text, re.I)):
        # NO PROCESS MODULE AT THE TOP OF THIS FILE (2026-09-24): the safety screen refused every build of this file
        # because it imported one at the top, and one import costs the whole build however narrow its use. The
        # search is the SAME search, done with the standard library: every .py file under the working directory,
        # the generated mirror under bundle/ and the interpreter's own caches left out, and the FIRST line that
        # defines the symbol. A file that cannot be read is skipped and a symbol that is not found is silence,
        # never a guess: the same fail-toward-saying-nothing direction as the rest of this function.
        first = []
        definition = re.compile(r"^[ \t]*(?:def|class)[ \t]+%s\b" % re.escape(sym))
        for base, dirnames, filenames in os.walk("."):
            dirnames[:] = sorted(d for d in dirnames
                                 if d not in ("bundle", ".git", "__pycache__", "node_modules",
                                              ".venv", "venv", ".mypy_cache", ".pytest_cache", ".tox"))
            for name in sorted(filenames):
                if not name.endswith(".py"):
                    continue
                rel = os.path.normpath(os.path.join(base, name))
                try:
                    with open(rel, encoding="utf-8", errors="replace") as fh:
                        for number, line in enumerate(fh, 1):
                            if definition.match(line):
                                first = ["%s:%d:%s" % (rel, number, line.rstrip("\n"))]
                                break
                except OSError:   # sbe: allow-silent an unreadable file is left out of the search, never guessed at
                    continue
                if first:
                    break
            if first:
                break
        if first:
            out.append("%s() is called new by the specification and is ALREADY DEFINED at %s. Call it, do not "
                       "redefine it." % (sym, first[0].split(":", 2)[0] + ":" + first[0].split(":", 2)[1]))
    return out


corrections = stale_claims(section, existing)
extra = ("Build ONLY sub unit %s of unit %s. Its own section of the specification names these files: existing %s; NEW %s. "
         "Earlier sub units of this unit may already be LANDED in the files shown: CALL what exists, never redefine it. "
         "If the section asks you to patch a SHARED existing module, keep every existing name, default, output and exit code, and make the change additive. "
         "Tests go in a NEW file BESIDE THE MODULE THEY TEST, named test_<module>_%s.py in that module's own folder. "
         "Use scripts/test_<name>_%s.py ONLY when the module under test is itself in scripts/. NEVER put a test in scripts/ "
         "that imports from products/ or plugin/: a scripts/ test is run on the PUBLIC export tree, which does not ship those "
         "packages, so it passes here and fails at the push gate. That has now happened twice in one day (test_vault_ui_census.py "
         "and test_vault_ui_read_surface.py), and the second one left a landing commit unpushed, which made every later landing "
         "refuse on parity and starved the build pool for 22 passes. Unless the section names a NEW test file, "
         "and done_check runs exactly that file. Never write under bundle/: the landing step regenerates the mirror."
         % (sub, unit, existing or "none", new or "none", re.sub(r"\W", "", sub).lower(), re.sub(r"\W", "", sub).lower()))
# The corrections go ABOVE the specification, because a builder reads the brief in order and the whole point is
# that it meets the truth before it meets the claim it contradicts.
corr = ("" if not corrections else
        "\n\nWHERE THE SPECIFICATION IS STALE, AND THE TREE WINS. These were checked against the real tree just\n"
        "now. Where this list and the specification below disagree, THIS LIST IS RIGHT and the specification is\n"
        "out of date, usually because an earlier sub unit already landed the work:\n"
        + "".join("  - %s\n" % c for c in corrections))
# THE UNIT, FROM THE WBS (owner 2026-09-24: briefs are per unit and from the epic). The row the plan carries for this
# unit is stated before the specification, so a worker reads WHY the unit exists and what closes it before HOW. An
# unreadable plan or a missing row is said so; brief_check refuses the brief, which is the honest answer.
def unit_block(unit_id, plan_path=os.environ.get("BROTHER_WBS", "docs/plan/BROTHER-1.1.0-LAUNCH-WBS.json")):
    try:
        with open(plan_path, encoding="utf-8") as fh:
            plan = json.load(fh)
        row = next(u for u in plan.get("units", []) if u.get("id") == unit_id)
    except (OSError, ValueError, StopIteration, AttributeError) as exc:
        return "THIS UNIT, FROM THE WBS: NO-DATA (%s: %s)\n" % (plan_path, str(exc)[:80])
    return ("THIS UNIT, FROM THE WBS (%s):\n  initiative: %s\n  unit %s: %s\n  objective: %s\n  closes when: %s\n  checker: %s\n"
            % (plan_path, str(plan.get("initiative", "NO-DATA"))[:200], unit_id, row.get("title", "NO-DATA"),
               str(row.get("objective", "NO-DATA"))[:1200], row.get("done_check", "NO-DATA"), str(row.get("checker", "NO-DATA"))[:600]))


# THE RIGHT CONTEXT WITHOUT NOISE (owner, 2026-09-27: "The right context without noise is everything"). A builder gets the
# unit's shared preamble and ITS OWN section, not every sibling's: one J1.a brief of 125 KB carried all four J1 sections.
# A section that names no file keeps the whole unit spec (it points at a sibling, the fallback above already follows it).
_first = re.search(r"^#{2,4} %s[.\-]" % re.escape(unit), spec, flags=re.M)
spec_text = ((spec[:_first.start()] if _first else "") + "\n" + section) if paths_in(section) else spec
_spec_head = "\n\nTHE SPECIFICATION (the unit's shared preamble and THIS sub unit's own section; the sibling sections are left out):\n"
# THE EPISODE BLOCK'S CEILING IN BYTES. It mirrors dream_episode.LESSON_BUDGET and sits inside brief_fit.NOTE_FLOOR,
# so the traced lessons never crowd out the failure evidence the repair rounds depend on (REQ-RL1-8).
LESSON_BUDGET = 6000


def lesson_block(unit: str, sub: str, runs_root: str, repo_root: str, now_utc: str,
                 budget: int = LESSON_BUDGET) -> str:
    """The eligible episodes of this sub unit, each traced to the receipt it was learned from (REQ-RL1-7).

    dream_episode is imported at load from the code root (model_router.code_root), so a code root without the
    plugin package, or a refused one, builds briefs as today with one NO-DATA line. Every run directory of this sub
    unit under runs_root (names starting '<sub>-') is read, newest by modification time first and never by the folder stamp;
    read_episodes then eligible with scope_of(repo_root, unit) and now_utc keep only the episodes this run may
    recall, and render_lessons bounds the block. No run directory of this sub unit at all returns '' (there is
    nothing to recall). Any failure (an argument that is not a non-empty string, a module that is missing, an
    unreadable runs_root, a raised step) returns one 'LESSONS NO-DATA: <reason>' line and never raises: a lesson
    that cannot be traced is withheld and the brief still builds (REQ-RL1-9)."""
    for label, value in (("unit", unit), ("sub", sub), ("runs_root", runs_root),
                         ("repo_root", repo_root), ("now_utc", now_utc)):
        if isinstance(value, bool) or not isinstance(value, str) or not value.strip():
            return "LESSONS NO-DATA: %s is not a non-empty string" % label
    if isinstance(budget, bool) or not isinstance(budget, int):
        return "LESSONS NO-DATA: budget is not an int number of bytes"
    try:
        module = _DE
        if module is None:
            if not os.path.isfile(_DREAM_EPISODE_PATH):
                return "LESSONS NO-DATA: dream_episode.py is not at %s" % _DREAM_EPISODE_PATH
            return "LESSONS NO-DATA: dream_episode.py at %s cannot be loaded: %s" % (_DREAM_EPISODE_PATH,
                                                                                     _DE_WHY[:200])
        names = os.listdir(runs_root)
        runs = []
        for name in names:
            if not name.startswith(sub + "-"):
                continue
            path = os.path.join(runs_root, name)
            if not os.path.isdir(path):
                continue
            try:
                runs.append((os.path.getmtime(path), name, path))
            except OSError:   # sbe: allow-silent an unstampable run is left out of the recall, never guessed at
                continue
        if not runs:
            return ""
        runs.sort(key=lambda run: (run[0], run[1]), reverse=True)
        scope = module.scope_of(repo_root, unit)
        kept = []
        for _stamp, _name, path in runs:
            rows = module.read_episodes(path)
            if rows is None:
                continue
            eligible_rows, _withheld = module.eligible(rows, scope, now_utc)
            kept.extend(eligible_rows)
        return module.render_lessons(kept, budget)
    except (OSError, ImportError, AttributeError, TypeError, ValueError, KeyError, RuntimeError) as exc:
        return "LESSONS NO-DATA: %s" % (str(exc)[:200] or type(exc).__name__)


# THE TRACED LESSONS SIT ABOVE THE SPECIFICATION (REQ-RL1-7), for the same reason the stale claims do: the builder
# meets the lesson learned from a receipt before it meets the claim that lesson corrects. Its bytes are part of body
# before the file budget below is computed, so the files still fit. A failure is one NO-DATA line, never a brief
# that fails to build (REQ-RL1-9).
# The lesson scope is the checkout the loop lands into, asked of git by model_router.repo_root(): three parents up from
# the deployed copy is the home folder, so every episode would read as another repository's and be withheld.
_REPO_ROOT = _R.repo_root()
_RUNS_ROOT = os.environ.get("BROTHER_UNIT_RUNS") or os.path.expanduser("~/.claude/evidence/unit-runs")
_LESSON_TEXT = lesson_block(unit, sub, _RUNS_ROOT, _REPO_ROOT,
                            datetime.datetime.now(datetime.timezone.utc).isoformat())
LESSONS = ("" if not _LESSON_TEXT else
           "\n\nLESSONS FROM EARLIER RUNS OF THIS SUB UNIT, each traced to its receipt:\n" + _LESSON_TEXT + "\n")
# THE GRADER'S SCREEN IN THE BRIEF (FX-09, BROTHER_BRIEF_SCREEN): generated from grade_build's own rules, never retyped,
# so it cannot drift from what the grader enforces. Off (unset, the default): "" and the brief is today's, byte for byte.
# On and it cannot be rendered, or it carries a private term: exit 2 and the runner parks the round WITHHELD with this
# reason, never a brief that silently lacks the screen it was asked to carry.
try:
    screen = "" if _G.brief_screen_mode() == "off" else "\n" + _G.screen_rules(existing) + "\n"
except (ValueError, OSError, RuntimeError) as exc:
    sys.stderr.write("NO-DATA: %s\n" % exc); sys.exit(2)
if screen and _G.private_hits(screen):
    sys.stderr.write("NO-DATA: the screen block carries a private term (or the private names list is unreadable)\n"); sys.exit(2)
body = head + "\n" + _LA.hostile_contract() + "\n" + unit_block(unit) + screen + "\n" + extra + corr + LESSONS + _spec_head + spec_text + "\n\nTHE REAL FILES:\n"
from brief_check import BUDGET as BRIEF_BUDGET   # one number for the builder and the gate; the runner appends up to 16000 after this
# THE FAILURE EVIDENCE KEEPS ITS ROOM (2026-09-27): the fitter reserves NOTE_FLOOR for the last round's failure lines under
# its CAP, but files were budgeted to the gate's 184,000 alone, which left about 15,000 for that evidence on a full brief.
import brief_fit as _BF
budget = min(BRIEF_BUDGET, _BF.CAP - _BF.NOTE_FLOOR) - len(body.encode())
# NO FILE LEAVES THE BRIEF WITHOUT ITS NAME (FX-09, 2026-09-29). The shares below split CONTENT bytes, but every block
# also spends its header and a newline, so the last block overflowed by a few dozen bytes and was dropped with no
# marker (three 95000 byte files: two blocks written, brief_check B1 REFUSED the third). Each file's header, newline
# and a NOT SHOWN marker are reserved first, so every file can always be at least NAMED; a budget that cannot even
# name them all is NO-DATA (exit 2, nothing written), never a brief missing a file.
OVERFLOW = ("[NOT SHOWN: this file did not fit its share of the brief. It EXISTS and is real. Do not guess its "
            "contents; list in unknowns any part of it you need.]")


def place(p, chunk, budget):
    """The block for p: chunk when its UTF-8 bytes fit budget, else the block naming p with OVERFLOW. The caller
    passes the bytes left after every later file's reservation, so the OVERFLOW block itself always fits."""
    if len(chunk.encode()) > budget:
        return "===== FILE: %s =====\n%s\n" % (p, OVERFLOW)
    return chunk


RESERVE = {p: len(("===== FILE: %s =====\n" % p).encode()) + 1 + len(OVERFLOW.encode()) for p in existing}
budget -= sum(RESERVE.values())
if RESERVE and budget < 0:   # no file to name keeps today's behaviour exactly
    sys.stderr.write("NO-DATA: %d files cannot all be named within the brief budget\n" % len(existing)); sys.exit(2)
def shares(paths, budget, floor=20000, cap=110000, secondary=()):
    """Bytes per file, allocated BY NEED rather than evenly, and GUARANTEED to fit the budget.

    THE FILES THE SECTION NAMES COME FIRST, the neighbour suites take what is left (2026-09-24, run 2: D1.8's
    section named 8 files and the neighbour rule added 14 test suites beside them; 22 floors summed past the
    budget, everything was scaled down together, and the sub unit's OWN test file kept 265 of its 5716 bytes
    while loop_bridge and model_worker read NOT SHOWN under a 7514 byte share. A neighbour exists so an edit keeps
    it green; it never outranks the file the edit is made to). `secondary` names the neighbours; they are
    allocated by the same rule out of whatever the named files leave, and can honestly come back NOT SHOWN.

    WHY, measured 2026-09-21 over 40 consecutive grades: 37 failed and 3 passed, and the dominant verdict was
    RED-WITHOUT-CODE NO, meaning the tests passed even without the builder's own code. 36 of the 37 failing
    grades named unshown or sliced out source in their own UNKNOWNS, in their own words, for example
    "scripts/dream_authorize.py is not shown; its internals were not mutated or verified" and "sliced out blocks
    in dream_policy.py prevent mutating step, depth, node, and AST tag checks".

    The brief already carries "your tests must fail without your code" as hard rule 4. The builders were not
    ignoring it; they COULD NOT COMPLY, because an even split handed every named file budget // n. A section
    naming five files gave each about 39 kB, so the one large shared module the sub unit actually had to test was
    truncated, and a test written against code you cannot see is a test that passes either way.

    IT MUST ALSO FIT. The dispatcher refuses a prompt over 200000 bytes and the caller leaves only what is left
    after the head and the spec. Both this and the even split it replaces could exceed that: n files each floored
    at 20000 sum past the budget whenever n is large, and an oversized brief comes back WITHHELD, which is one of
    the blocked states this change exists to remove. So the floor is capped at the file's own size (a file
    smaller than the floor is complete, not starved) and the total is scaled to fit as a last resort."""
    secondary = set(secondary)
    if secondary and [p for p in paths if p not in secondary]:
        out = shares([p for p in paths if p not in secondary], budget, floor, cap)
        out.update(shares([p for p in paths if p in secondary], max(0, budget - sum(out.values())), floor, cap))
        return out
    need = {}
    for path in paths:
        try:
            need[path] = min(os.path.getsize(path), cap)
        except OSError:
            need[path] = floor          # unreadable size neither starves the file nor favours it
    if not paths:
        return {}
    total_need = sum(need.values()) or 1
    out = {}
    for path in paths:
        want = int(budget * need[path] / total_need)
        want = min(want, need[path])                  # never pad a file past its own size
        out[path] = max(want, min(floor, need[path]))  # the floor never exceeds the file itself
    # Hand any leftover to the files still short of what they need, largest need first: this is what gives the
    # big shared module its room once the small files have taken only what they are.
    spare = budget - sum(out.values())
    if spare > 0:
        for path in sorted(paths, key=lambda q: -need[q]):
            if spare <= 0:
                break
            add = min(spare, need[path] - out[path])
            if add > 0:
                out[path] += add
                spare -= add
    # A FLOOR RAISED A SMALL FILE PAST ITS PROPORTIONAL SHARE, so the sum can exceed the budget while every floor still
    # fits it (2026-09-29: a 33859 byte and a 6289 byte file under 40000; the scaling below cut the small file to 6285,
    # a stub). The excess comes out of the shares ABOVE their floor first, largest excess first; a floor is cut only
    # by the last resort below, when the floors themselves do not fit (and then everything scales together, which keeps
    # the largest need ahead of its siblings: trimming it to its floor first would tie them).
    over = sum(out.values()) - budget
    if sum(min(floor, need[q]) for q in paths) > budget:
        over = 0
    for path in sorted(paths, key=lambda q: -(out[q] - min(floor, need[q]))):
        if over <= 0:
            break
        give = min(over, out[path] - min(floor, need[path]))
        if give > 0:
            out[path] -= give
            over -= give
    # LAST RESORT, and it is a real case: many named files whose own floors already sum past the budget. Scale
    # everything down together rather than letting the brief overflow and come back WITHHELD.
    over = sum(out.values()) - budget
    if over > 0:
        scale = budget / max(1, sum(out.values()))
        for path in paths:
            out[path] = max(1, int(out[path] * scale))
        while sum(out.values()) > budget:
            worst = max(paths, key=lambda q: out[q])
            out[worst] -= 1
    return out


PER = shares(existing, budget, secondary=neighbours)
budget += sum(RESERVE.values())   # the reservation is spent below, block by block: a file's own share plus its name
owed = sum(RESERVE.values())      # what the files not yet placed are still owed, so each can always be named
for p in existing:
    owed -= RESERVE[p]
    per = PER.get(p, 20000)
    if p.endswith(".py"):
        try:
            text, dropped = slice_source(p, spec, per)
        except (SystemExit, ValueError, RuntimeError):
            # the whole unit spec names more of this file than fits: keep the blocks THIS sub unit's own section names (still verbatim, dropped blocks still marked by name)
            try:
                text, dropped = slice_source(p, section, per)
            except (SystemExit, ValueError, RuntimeError) as exc:
                # THE RETRY CAN FAIL TOO, and until 2026-09-21 that exception escaped and killed the whole
                # lane. Three sub units (D1.5, D3.4, L3.1) sat blocked for a day having never reached a model,
                # because one shared module they read could not be sliced small enough: jev_seam and bm_vault
                # have more module level code than their share of the budget. One unfittable file must not cost
                # the lane. It is left out BY NAME, exactly as a file carrying a private term already is right
                # below, so the builder knows the file exists and knows not to guess at it.
                text, dropped = ("[NOT SHOWN: this file could not be sliced under its %d byte share of the "
                                 "brief (%s). It EXISTS and is real. Do not guess its contents: read only what "
                                 "the specification says about it, and list in unknowns any part of it you "
                                 "need.]" % (per, str(exc)[:120]), [])
    else:
        # CUT BY BYTES, MARKED (FX-09): a share is bytes, and a cut by characters let non ASCII text overrun it; the cut
        # drops a split trailing character. A file that is not UTF-8 at all is named with its reason, never a crash.
        try:
            with open(p, "rb") as fh:
                raw = fh.read()
            raw.decode("utf-8")
            text = raw[:per].decode("utf-8", "ignore")
            if len(raw) > per:
                text += "\n[NOT SHOWN past byte %d of %d: the rest of this file exists and is real]" % (per, len(raw))
        except (OSError, UnicodeDecodeError) as exc:
            text = ("[NOT SHOWN: this file is not UTF-8 text or cannot be read (%s). It EXISTS and is real. Do not guess "
                    "its contents; list in unknowns any part of it you need.]" % type(exc).__name__)
        dropped = []
    chunk = "===== FILE: %s =====\n%s\n" % (p, text)
    if _G.private_hits(chunk):
        # one file with a private term must not hold the whole brief, and must never be sent: it is left out BY NAME, so the builder knows it exists
        chunk = "===== FILE: %s =====\n[NOT SHOWN: this file carries a private term and never leaves the machine. Do not guess its contents: read only what the specification says about it, and list in unknowns any field of it you need.]\n" % p
    chunk = place(p, chunk, budget - owed)
    body += chunk; budget -= len(chunk.encode())
body += "\n\nBUILD ONLY THIS SUB UNIT: %s\n" % sub
with open(out, "w", encoding="utf-8") as f:
    f.write(body)
print("\n".join(paths))
