#!/usr/bin/env python3
"""gauntlet_frozen: refuse to score a corpus whose hash moved since the
frozen gauntlet spec was frozen.

Row S27 (docs/plan/READINESS-ROADMAP-2026-08-29.json) found that the six
specs under benchmarks/gauntlets/ carried no corpus hash at all, so nothing
stopped a runner from scoring a corpus that had silently changed since the
spec was written. Every spec now carries a `frozen` block: `corpus` (the
data file it scores, or the sentence "none: cases are generated by the
runner" for a gauntlet whose cases are built at run time rather than read
from disk), `corpus_sha1`, `frozen_at` and `frozen_by`.

WHAT GETS HASHED. When `corpus` names a real file, corpus_sha1 is the sha1
of that file's raw bytes. When `corpus` is the "none: ..." sentence, there
is no separate data file to hash, so corpus_sha1 is the sha1 of the spec's
own content (the seed definition itself: workload_families,
seeded_conditions, scoring_rubric and everything else) with the `frozen`
key excluded, since that key did not exist at the moment the hash was
taken. A later edit to the spec's seed definition moves this hash exactly
as a changed corpus file would move the other kind, which is the point.

Usage: python3 scripts/gauntlet_frozen.py <spec.json>
  exit 0, "frozen: OK <sha1>"                          -- hash matches
  exit 1, "REFUSED: corpus hash moved: spec <a> tree <b>" -- hash moved
  exit 2, "NO-DATA: ..."                                -- no frozen block,
                                                            or a named
                                                            corpus file this
                                                            tree does not
                                                            have

A runner scoring one of these specs calls check(spec_path) before it scores
anything and refuses (or reports NO-DATA) exactly the way this CLI does,
rather than reimplementing the comparison.
"""
import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

NODATA = "NO-DATA"
GENERATED = "none: cases are generated by the runner"


def _sha1_bytes(payload):
    return hashlib.sha1(payload).hexdigest()


def _sha1_file(path):
    digest = hashlib.sha1()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(65536), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _spec_hash(spec):
    rest = {k: v for k, v in spec.items() if k != "frozen"}
    payload = json.dumps(rest, sort_keys=True, ensure_ascii=False)
    return _sha1_bytes(payload.encode("utf-8"))


def check(spec_path):
    """Recompute the frozen corpus hash for the spec at spec_path.

    Returns the matching sha1 hex string when the corpus's current hash
    equals what the spec froze. Returns a NO-DATA sentence (a plain string
    starting with "NO-DATA") when the spec has no frozen block, or when the
    frozen block names a real corpus file this tree does not have. Raises
    ValueError, message "REFUSED: corpus hash moved: spec <a> tree <b>",
    when the corpus is present but its hash no longer matches.
    """
    with open(spec_path, encoding="utf-8") as handle:
        spec = json.load(handle)

    frozen = spec.get("frozen")
    if not isinstance(frozen, dict) or not frozen:
        return "%s: %s: spec has no frozen block" % (NODATA, spec_path)

    corpus = frozen.get("corpus")
    expected = frozen.get("corpus_sha1")
    if not corpus or not expected:
        return ("%s: %s: frozen block names no corpus or no corpus_sha1"
                % (NODATA, spec_path))

    if corpus == GENERATED or corpus.startswith("none:"):
        actual = _spec_hash(spec)
    else:
        target = os.path.join(ROOT, corpus)
        if not os.path.exists(target):
            return ("%s: %s: corpus path does not exist: %s"
                    % (NODATA, spec_path, corpus))
        actual = _sha1_file(target)

    if actual != expected:
        raise ValueError("REFUSED: corpus hash moved: spec %s tree %s"
                          % (expected, actual))
    return actual


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv:
        print("usage: gauntlet_frozen.py <spec.json>")
        return 2

    try:
        result = check(argv[0])
    except ValueError as exc:
        print(str(exc))
        return 1

    if result.startswith(NODATA):
        print(result)
        return 2

    print("frozen: OK %s" % result)
    return 0


if __name__ == "__main__":
    sys.exit(main())
