"""gen_door_table: the door's cell table is generated, never hand-typed.

R-5 of the persona dogfood register. The one door shipped a six-verb table
typed by hand into bundle/commands/brother.md, so ten capabilities a user can
invoke today (kickoff, design, work, adopt, handover, learn,
prove-this-change, spec-and-data-prep, brief, decisions) had no cell at all,
and an ask that named one of them fell through the table into `start`.

A hand-typed table of another tree's contents is a copy that rots the moment
that tree changes, and nothing in the repository noticed. So the table is
derived from the source of truth it was copying: the `name:` frontmatter of
every bundle/skills/*/SKILL.md, the skills the ONE plugin installs.

ONE PLUGIN (2026-09-30, docs/architecture/ADR-ONE-PLUGIN-HOOKS.md). After
1.1.0 the user installs `brother` alone, so every cell is `/brother:<skill>`.
A bundle skill named `<product>-<verb>` fills the `<product>` column of row
`<verb>`; the `brotherme-*` skills are the same verbs as `brothermode-*`
(the command mirrors, see codex_surface.py) and add no row. `--check` exits 1
when the shipped table differs from a fresh render, like every generator.

WHAT IT WRITES, AND WHERE IT STOPS. Only the region between the two sentinel
comments in the door file is rewritten. Everything outside those sentinels is
prose a person wrote and this tool must never touch, which is why a door with
no sentinels is an error (exit 2) rather than an append: appending a table to
a file that lost its markers would leave two tables, and a reader would
follow whichever came first.

WHICH INVOCATION A CELL CARRIES. Every bundle skill registers as a typeable
entry under its own name (the generated aliases carry no `user-invocable:
false`), so the cell is `/brother:<name>`. A skill that does say it is not
typeable has its cell say `skill brother:<name>`, which is the truth: that
capability is reachable by the assistant and not by typing.
scripts/test_door_routing_prose.py checks every row against bundle/skills,
so a cell can never promise an entry the bundle does not install.

WHAT IT IS NOT. It is not a menu. The door's own rule ("Never a menu of
skills or commands") is unchanged: this table is what the assistant reads to
place an ask, and the person still gets one question.

Python 3, standard library only. No network.
"""
import argparse
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOOR = os.path.join(ROOT, "bundle", "commands", "brother.md")

#: The one plugin every cell names.
PLUGIN = "brother"
#: Column order is the door's own: the project column, then the assurance
#: one. A bundle skill `<product>-<verb>` fills column <product>.
PRODUCTS = ("brothermode", "brothersbe")
LABELS = dict(brothermode="Project (BrotherMode)",
              brothersbe="Assurance (BrotherSBE)")
#: Bundle skill prefixes that add no row: the brotherme-* command mirrors
#: duplicate the brothermode-* verbs, and using-brother is the door itself.
NO_ROW = ("brotherme-", "using-")

BEGIN = "<!-- BEGIN CELL TABLE, generated by scripts/gen_door_table.py -->"
END = "<!-- END CELL TABLE -->"

#: The verbs the door has always led with, kept at the top so the familiar
#: rows stay where a reader's eye already goes. Everything else follows in
#: sorted order, so the output is a function of the skills on disk alone.
CORE_ORDER = ("start", "status", "next", "review", "deliver", "verify", "help")

#: A verb one product has and the other does not. Never a dash: the standing
#: rule forbids em and en dashes in every surface.
ABSENT = "(none)"

#: The retired product namespaces (brothermode, brothersbe, brotherds), with or without the slash. A path
#: segment, a dotted name or a hyphenated one before it is not a command mention, hence the lead class.
RETIRED_NAMESPACE = r"(^|[^A-Za-z0-9_./-])/?brother(mode|sbe|ds):[a-z]"
_RETIRED = re.compile(RETIRED_NAMESPACE)
#: Where a user can read a name: every shipped surface of the one plugin, relative to the repository root.
USER_SCOPES = tuple("bundle/" + part for part in (
    "commands", "skills", "codex-skills", "agents", "rules", "hooks", "runtime"))
#: The one allowlist (OP1 5.3): a persisted record key prefix, `"brothermode:...evidence:%s..."`, inside a
#: Python string literal. Renaming it would orphan stored evidence. Nothing else is skipped.
_KEY_LITERAL = re.compile(r"\"[^\"\n]*evidence:%s[^\"\n]*\"|'[^'\n]*evidence:%s[^'\n]*'")
_MENTION = re.compile(r"/brother:([a-z][a-z0-9-]+)")

NAME_LINE = re.compile(r"^name:\s*(\S+)\s*$", re.M)
NOT_TYPEABLE = re.compile(r"^user-invocable:\s*false\s*$", re.M | re.I)


def _frontmatter(text, path):
    """The frontmatter block of a SKILL.md, as text.

    A file with no frontmatter is an error rather than an empty string: it
    would silently contribute no row, which is exactly the drift this tool
    exists to end."""
    if not text.startswith("---"):
        raise ValueError("%s has no frontmatter, so it names no skill" % path)
    end = text.find("\n---", 3)
    if end == -1:
        raise ValueError("%s has an unterminated frontmatter block" % path)
    return text[:end]


def read_skill(path):
    """(name, typeable) for one SKILL.md."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    front = _frontmatter(text, path)
    match = NAME_LINE.search(front)
    if not match:
        raise ValueError("%s carries no `name:` line, so it has no cell" % path)
    return match.group(1), not NOT_TYPEABLE.search(front)


def invocation(name, typeable):
    """What a cell says for one bundle skill. See the module docstring."""
    if typeable:
        return "/%s:%s" % (PLUGIN, name)
    return "skill %s:%s" % (PLUGIN, name)


def split_name(name):
    """(product, verb) for a bundle skill name, or None when it adds no
    row (a brotherme-* mirror, the door, or an unknown prefix)."""
    if name.startswith(NO_ROW):
        return None
    for product in PRODUCTS:
        if name.startswith(product + "-"):
            return product, name[len(product) + 1:]
    return None


def collect(root=ROOT):
    """The cells, as {product: {verb: invocation}}, read off the bundle."""
    cells = dict((product, dict()) for product in PRODUCTS)
    pattern = os.path.join(root, "bundle", "skills", "*", "SKILL.md")
    for path in sorted(glob.glob(pattern)):
        name, typeable = read_skill(path)
        split = split_name(name)
        if split is None:
            continue
        product, verb = split
        cells[product][verb] = invocation(name, typeable)
    for product in PRODUCTS:
        if not cells[product]:
            raise ValueError(
                "no %s-* skills found under bundle/skills, so the table would "
                "silently lose a whole column" % product)
    return cells


def _is_record_key(line, path):
    """True when every retired match on the line sits inside an allowlisted key literal of a .py file."""
    if not path.endswith(".py"):
        return False
    spans = [m.span() for m in _KEY_LITERAL.finditer(line)]
    found = list(_RETIRED.finditer(line))
    return bool(found) and all(
        any(a <= m.end(1) and m.end() <= b for a, b in spans) for m in found)


def retired_namespace_hits(root, scopes):
    """(relative path, line number, line) for every retired namespace in every UTF-8 text file under the
    scopes (folders relative to root). A scope that is not a folder is an error, never an empty scan."""
    if not isinstance(root, str) or not root:
        raise ValueError("retired_namespace_hits needs the root as a non-empty str")
    if not isinstance(scopes, (tuple, list)) or not scopes or not all(
            isinstance(s, str) and s for s in scopes):
        raise ValueError("retired_namespace_hits needs scopes as a non-empty tuple of str")
    hits = []
    for scope in scopes:
        top = os.path.join(root, scope)
        if not os.path.isdir(top):
            raise ValueError("scope %s is not a folder under %s" % (scope, root))
        for dirpath, dirnames, filenames in os.walk(top):
            dirnames.sort()
            for name in sorted(filenames):
                path = os.path.join(dirpath, name)
                rel = os.path.relpath(path, root)
                try:
                    with open(path, "rb") as fh:
                        text = fh.read().decode("utf-8")
                except (UnicodeDecodeError, OSError):
                    continue
                for number, line in enumerate(text.splitlines(), 1):
                    if _RETIRED.search(line) and not _is_record_key(line, rel):
                        hits.append((rel, number, line))
    return hits


def dead_mentions(root):
    """Problem strings for every `/brother:<name>` in commands and skills that names no skill or command."""
    base = os.path.join(root, "bundle")
    known = set()
    for path in glob.glob(os.path.join(base, "skills", "*", "SKILL.md")):
        known.add(read_skill(path)[0])
    for path in glob.glob(os.path.join(base, "commands", "*.md")):
        known.add(os.path.basename(path)[:-3])
    problems = []
    for scope in ("commands", "skills"):
        pattern = os.path.join(base, scope, "**", "*.md")
        for path in sorted(glob.glob(pattern, recursive=True)):
            with open(path, encoding="utf-8") as fh:
                text = fh.read()
            for name in sorted(set(_MENTION.findall(text))):
                if name not in known:
                    problems.append("%s names /brother:%s, which is no skill or command"
                                    % (os.path.relpath(path, root), name))
    return problems


def check_table(root=ROOT):
    """The importable --check: one problem string per defect, [] when clean. A missing sentinel, an
    unreadable bundle or a missing door is a problem, never clean."""
    if not isinstance(root, str) or not root:
        return ["check_table needs the root as a non-empty str"]
    door = os.path.join(root, "bundle", "commands", "brother.md")
    problems = []
    try:
        text, updated = rendered_door(door, render_table(collect(root=root)))
        if text != updated:
            problems.append("DRIFT: %s does not match a fresh render of bundle/skills" % door)
    except (ValueError, OSError) as exc:
        problems.append("%s" % exc)
    try:
        with open(door, encoding="utf-8") as fh:
            for number, line in enumerate(fh.read().splitlines(), 1):
                if _RETIRED.search(line):
                    problems.append("%s:%d speaks a retired namespace: %s" % (door, number, line.strip()))
        problems.extend(dead_mentions(root))
    except (ValueError, OSError) as exc:
        problems.append("%s" % exc)
    return problems


def row_order(cells):
    """Every verb either product ships, core rows first, then sorted."""
    names = set()
    for found in cells.values():
        names.update(found)
    lead = [n for n in CORE_ORDER if n in names]
    return lead + sorted(names.difference(lead))


def render_table(cells):
    """The markdown table, as text ending in a newline. N columns, one per
    entry in PRODUCTS, built from a loop rather than two fixed slots, so a
    third (or further) product needs no change here."""
    header = "| Verb | %s |" % " | ".join(LABELS[product] for product in PRODUCTS)
    lines = [header, "|---|" + "---|" * len(PRODUCTS)]
    for name in row_order(cells):
        columns = []
        for product in PRODUCTS:
            entry = cells[product].get(name)
            columns.append("`%s`" % entry if entry else ABSENT)
        lines.append("| %s | %s |" % (name, " | ".join(columns)))
    return "\n".join(lines) + "\n"


def rendered_door(door_path, table):
    """(current text, text with the sentinel block replaced)."""
    with open(door_path, encoding="utf-8") as fh:
        text = fh.read()
    start = text.find(BEGIN)
    end = text.find(END)
    if start == -1 or end == -1 or end < start:
        raise ValueError(
            "%s does not carry both sentinels (%r then %r), so there is no "
            "block to rewrite" % (door_path, BEGIN, END))
    return text, text[:start + len(BEGIN)] + "\n" + table + text[end:]


def rewrite(door_path, table):
    """Replace the sentinel block in the door. True if the bytes moved."""
    text, updated = rendered_door(door_path, table)
    if updated == text:
        return False
    with open(door_path, "w", encoding="utf-8") as fh:
        fh.write(updated)
    return True


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--door", default=DOOR,
                        help="the command file to rewrite")
    parser.add_argument("--root", default=ROOT,
                        help="the repository whose products are read")
    parser.add_argument("--print", dest="print_only", action="store_true",
                        help="print the table and write nothing")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 when the door's table is stale, "
                             "writing nothing")
    args = parser.parse_args(argv)
    try:
        cells = collect(root=args.root)
        table = render_table(cells)
        if args.print_only:
            sys.stdout.write(table)
            return 0
        if args.check:
            text, updated = rendered_door(args.door, table)
            if text != updated:
                sys.stderr.write("gen_door_table: DRIFT: %s does not match "
                                 "a fresh render of bundle/skills\n"
                                 % args.door)
                return 1
            dead = dead_mentions(args.root)
            if dead:
                sys.stderr.write("gen_door_table: DEAD NAME: %s\n" % "; ".join(dead))
                return 1
            sys.stdout.write("gen_door_table: %s is current (%d cell "
                             "row(s))\n" % (args.door, len(row_order(cells))))
            return 0
        changed = rewrite(args.door, table)
    except (ValueError, OSError) as exc:
        sys.stderr.write("gen_door_table: %s\n" % exc)
        return 2
    sys.stdout.write("gen_door_table: %s %d cell row(s) in %s\n"
                     % ("rewrote" if changed else "already current",
                        len(row_order(cells)), args.door))
    return 0


if __name__ == "__main__":
    sys.exit(main())
