"""gen_door_table: the door's cell table is generated, never hand-typed.

R-5 of the persona dogfood register. The one door shipped a six-verb table
typed by hand into bundle/commands/brother.md, so ten capabilities a user can
invoke today (kickoff, design, work, adopt, handover, learn,
prove-this-change, spec-and-data-prep, brief, decisions) had no cell at all,
and an ask that named one of them fell through the table into `start`.

A hand-typed table of another tree's contents is a copy that rots the moment
that tree changes, and nothing in the repository noticed. So the table is
derived from the source of truth it was copying: the `name:` frontmatter of
every products/{brothermode,brothersbe}/skills/*/SKILL.md.

WHAT IT WRITES, AND WHERE IT STOPS. Only the region between the two sentinel
comments in the door file is rewritten. Everything outside those sentinels is
prose a person wrote and this tool must never touch, which is why a door with
no sentinels is an error (exit 2) rather than an append: appending a table to
a file that lost its markers would leave two tables, and a reader would
follow whichever came first.

WHICH INVOCATION A CELL CARRIES. A skill whose frontmatter does not say
`user-invocable: false` registers as a typeable entry under its own name, so
the cell is `/<product>:<name>`. One that does say it is not typeable has its
cell carry the `brotherme-<name>` command that fronts it, where that command
exists on disk. Where neither exists the cell says `skill <product>:<name>`,
which is the truth: that capability is reachable by the assistant and not by
typing. scripts/test_door_routing_prose.py checks every slash form against
bundle/MANIFEST.json, so a cell can never promise an entry the bundle does
not install.

WHAT IT IS NOT. It is not a menu. The door's own rule ("Never a menu of
skills or commands") is unchanged: this table is what the assistant reads to
place an ask, and the person still gets one question.

Python 3, standard library only. No network.
"""
import argparse
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOOR = os.path.join(ROOT, "bundle", "commands", "brother.md")

#: Column order is the door's own: the project column, then the assurance one.
PRODUCTS = ("brothermode", "brothersbe")
LABELS = dict(brothermode="Project (BrotherMode)", brothersbe="Assurance (BrotherSBE)")

BEGIN = "<!-- BEGIN CELL TABLE, generated by scripts/gen_door_table.py -->"
END = "<!-- END CELL TABLE -->"

#: The verbs the door has always led with, kept at the top so the familiar
#: rows stay where a reader's eye already goes. Everything else follows in
#: sorted order, so the output is a function of the skills on disk alone.
CORE_ORDER = ("start", "status", "next", "review", "deliver", "verify", "help")

#: A verb one product has and the other does not. Never a dash: the standing
#: rule forbids em and en dashes in every surface.
ABSENT = "(none)"

NAME_LINE = re.compile(r"^name:\s*(\S+)\s*$", re.M)
NOT_TYPEABLE = re.compile(r"^user-invocable:\s*false\s*$", re.M | re.I)


def _frontmatter(text, path):
    """The frontmatter block of a SKILL.md, as text.

    A file with no frontmatter is an error rather than an empty string: it
    would silently contribute no row, which is exactly the drift this tool
    exists to end."""
    if not text.startswith("---"):
        raise ValueError("%s has no frontmatter, so it names no skill" % path)
    end = text.find("\n---", 3)
    if end == -1:
        raise ValueError("%s has an unterminated frontmatter block" % path)
    return text[:end]


def read_skill(path):
    """(name, typeable) for one SKILL.md."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    front = _frontmatter(text, path)
    match = NAME_LINE.search(front)
    if not match:
        raise ValueError("%s carries no `name:` line, so it has no cell" % path)
    return match.group(1), not NOT_TYPEABLE.search(front)


def invocation(product, name, typeable, root=ROOT):
    """What a cell says for one skill. See the module docstring."""
    if typeable:
        return "/%s:%s" % (product, name)
    command = os.path.join(
        root, "products", product, "commands", "brotherme-%s.md" % name)
    if os.path.isfile(command):
        return "/%s:brotherme-%s" % (product, name)
    return "skill %s:%s" % (product, name)


def collect(root=ROOT):
    """The cells, as {product: {skill name: invocation}}, read off disk."""
    cells = dict()
    for product in PRODUCTS:
        pattern = os.path.join(root, "products", product, "skills", "*",
                               "SKILL.md")
        found = dict()
        for path in sorted(glob.glob(pattern)):
            name, typeable = read_skill(path)
            found[name] = invocation(product, name, typeable, root=root)
        if not found:
            raise ValueError(
                "no skills found under products/%s/skills, so the table would "
                "silently lose a whole column" % product)
        cells[product] = found
    return cells


def row_order(cells):
    """Every verb either product ships, core rows first, then sorted."""
    names = set()
    for found in cells.values():
        names.update(found)
    lead = [n for n in CORE_ORDER if n in names]
    return lead + sorted(names.difference(lead))


def render_table(cells):
    """The markdown table, as text ending in a newline."""
    header = "| Verb | %s | %s |" % (LABELS[PRODUCTS[0]], LABELS[PRODUCTS[1]])
    lines = [header, "|---|---|---|"]
    for name in row_order(cells):
        columns = []
        for product in PRODUCTS:
            entry = cells[product].get(name)
            columns.append("`%s`" % entry if entry else ABSENT)
        lines.append("| %s | %s | %s |" % (name, columns[0], columns[1]))
    return "\n".join(lines) + "\n"


def rewrite(door_path, table):
    """Replace the sentinel block in the door. True if the bytes moved."""
    with open(door_path, encoding="utf-8") as fh:
        text = fh.read()
    start = text.find(BEGIN)
    end = text.find(END)
    if start == -1 or end == -1 or end < start:
        raise ValueError(
            "%s does not carry both sentinels (%r then %r), so there is no "
            "block to rewrite" % (door_path, BEGIN, END))
    updated = text[:start + len(BEGIN)] + "\n" + table + text[end:]
    if updated == text:
        return False
    with open(door_path, "w", encoding="utf-8") as fh:
        fh.write(updated)
    return True


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--door", default=DOOR,
                        help="the command file to rewrite")
    parser.add_argument("--root", default=ROOT,
                        help="the repository whose products are read")
    parser.add_argument("--print", dest="print_only", action="store_true",
                        help="print the table and write nothing")
    args = parser.parse_args(argv)
    try:
        cells = collect(root=args.root)
        table = render_table(cells)
        if args.print_only:
            sys.stdout.write(table)
            return 0
        changed = rewrite(args.door, table)
    except (ValueError, OSError) as exc:
        sys.stderr.write("gen_door_table: %s\n" % exc)
        return 2
    sys.stdout.write("gen_door_table: %s %d cell row(s) in %s\n"
                     % ("rewrote" if changed else "already current",
                        len(row_order(cells)), args.door))
    return 0


if __name__ == "__main__":
    sys.exit(main())
