#!/usr/bin/env python3
"""ACC4.a: classify every open pull request as LANDED, SUPERSEDED, LIVE,
IDLE-UNCLASSIFIED or NO-DATA, and generate the owner's park list.

Spec: docs/plan/specs/ACC4.md. READ ONLY: the only gh verbs this module runs
are `pr list` and `pr view`; a write verb (close, edit, comment, merge) is
refused with ValueError before gh is called. Landed is proven by git
(`merge-base --is-ancestor`, then `git cherry`), never by a title. A listing
on the owner's close list is corroborated (idle at least IDLE_DAYS and
CONFLICTING, or landed), never trusted. A missing close list is NO-DATA,
never an empty list.

Usage, from the repository root (git must resolve `--main-ref`, fetch first):

    python3 -B scripts/pr_park_triage.py [--repo OWNER/NAME] [--main-ref hub/main]
        [--close-list PATH] [--out docs/plan/ACC4-PARK-LIST.txt] [--limit 200]

Exit 0 with the list written and one line per pull request printed; exit 2
NO-DATA when gh or the close list cannot be read.

Python 3, stdlib only. No em or en dashes anywhere in this file.
"""
import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from typing import Dict, List, Optional

IDLE_DAYS = 7  # type: int
REPO = "khalilmaaouni/brother-hub"
LIST_LIMIT = 200
LIST_FIELDS = "number,state,updatedAt,isDraft,mergeable,headRefName,headRefOid,baseRefName"
PARK_LIST = os.path.join("docs", "plan", "ACC4-PARK-LIST.txt")
PARK_HEADER = ("# <number> <reason>: generated by scripts/pr_park_triage.py, the input of "
               "scripts/close_superseded.sh. LANDED and SUPERSEDED pull requests only.")
READ_VERBS = ("list", "view")
WRITE_VERBS = ("close", "edit", "comment", "merge")
CLASSES = ("LANDED", "SUPERSEDED", "LIVE", "IDLE-UNCLASSIFIED", "NO-DATA")
_CHERRY_LINE = re.compile(r"^[+-] [0-9a-f]{7,40}$")


def refuse_write_verb(verb):
    """The one place every gh call routes through: a write verb never reaches gh."""
    if verb in WRITE_VERBS or verb not in READ_VERBS:
        raise ValueError("pr_park_triage is read only: gh pr %s refused" % verb)
    return verb


def gh_pr(verb, args, repo=REPO, gh_bin="gh"):
    """Run `gh pr <verb> ... -R repo` (read verbs only). Returns (exit, stdout, stderr)."""
    refuse_write_verb(verb)
    cmd = [gh_bin, "pr", verb] + list(args) + ["-R", repo]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, stdin=subprocess.DEVNULL)
    except OSError as exc:
        return 127, "", "%s: %s" % (gh_bin, exc)
    return proc.returncode, proc.stdout, proc.stderr


def fetch_open_prs(repo=REPO, limit=LIST_LIMIT, gh_bin="gh"):
    """The open list, or None (NO-DATA) when gh cannot answer or answers badly."""
    code, out, err = gh_pr("list", ["--state", "open", "--limit", str(limit), "--json", LIST_FIELDS],
                           repo=repo, gh_bin=gh_bin)
    if code != 0:
        return None, "gh pr list exit %d: %s" % (code, err.strip() or out.strip())
    try:
        prs = json.loads(out)
    except ValueError as exc:
        return None, "gh pr list printed no JSON: %s" % exc
    if not isinstance(prs, list) or not all(isinstance(p, dict) and "number" in p for p in prs):
        return None, "gh pr list JSON is not a list of pull requests"
    return prs, ""


def _git(args, cwd):
    try:
        proc = subprocess.run(["git"] + list(args), cwd=cwd, capture_output=True, text=True,
                              stdin=subprocess.DEVNULL)
    except OSError:
        return 127, ""
    return proc.returncode, proc.stdout


def is_landed(head_oid, main_ref="hub/main", cwd=None):
    # type: (str, str, Optional[str]) -> Optional[bool]
    """True when head is an ancestor of main_ref or every commit of head is
    patch equal on it (git cherry prints only `-` lines). False only when git
    says so (exit 1, or a `+` line). None for any other exit, an absent
    object, an empty or unparseable cherry output: never True by default."""
    if not head_oid or not re.fullmatch(r"[0-9a-f]{7,40}", head_oid):
        return None
    code, _ = _git(["merge-base", "--is-ancestor", head_oid, main_ref], cwd)
    if code == 0:
        return True
    if code != 1:
        return None
    code, out = _git(["cherry", main_ref, head_oid], cwd)
    if code != 0:
        return None
    lines = [line for line in out.splitlines() if line.strip()]
    if not lines or any(not _CHERRY_LINE.match(line) for line in lines):
        return None
    return not any(line.startswith("+") for line in lines)


def _parse_updated(value):
    try:
        return datetime.strptime(str(value), "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
    except (TypeError, ValueError):
        return None


def idle_days_of(pr, now):
    # type: (Dict[str, object], datetime) -> Optional[int]
    """Whole days since updatedAt; None when unparseable or in the future."""
    updated = _parse_updated(pr.get("updatedAt"))
    if updated is None or updated > now:
        return None
    return (now - updated).days


def classify_pr(pr, landed, listed_reason, idle_days):
    # type: (Dict[str, object], Optional[bool], Optional[str], Optional[int]) -> str
    """Exactly one of CLASSES. idle_days is this pull request's own idle count
    (None when unknown); IDLE_DAYS is the line it is measured against."""
    if landed is None:
        return "NO-DATA"
    if landed is True:
        return "LANDED"
    if idle_days is None:
        return "NO-DATA"
    if listed_reason is not None:
        corroborated = idle_days >= IDLE_DAYS and str(pr.get("mergeable")) == "CONFLICTING"
        return "SUPERSEDED" if corroborated else "IDLE-UNCLASSIFIED"
    if idle_days < IDLE_DAYS:
        return "LIVE"
    return "IDLE-UNCLASSIFIED"


def read_close_list(path):
    # type: (str) -> Dict[int, str]
    """The owner's `<number> <reason>` lines; `#` lines and blanks skipped.
    Raises FileNotFoundError (or OSError) when unreadable: never an empty dict."""
    listed = {}  # type: Dict[int, str]
    with open(path, encoding="utf-8") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            number, _, reason = line.partition(" ")
            if number.isdigit() and reason.strip():
                listed[int(number)] = reason.strip()
    return listed


def _text(value):
    return " ".join(str(value if value is not None else "").split())


def triage(prs, listed, main_ref="hub/main", now_iso="", close_list_path=None, cwd=None, verb="list"):
    # type: (List[Dict[str, object]], Dict[int, str], str, str, Optional[str], Optional[str], str) -> List[Dict[str, str]]
    """One row per pull request: number, class, reason, idle_days, mergeable,
    head, draft. Read only: `verb` names the gh verb the caller fetched with
    and a write verb is refused. A close_list_path that cannot be read raises."""
    refuse_write_verb(verb)
    listed = dict(listed or {})
    if close_list_path is not None:
        listed.update(read_close_list(close_list_path))
    now = _parse_updated(now_iso) if now_iso else datetime.now(timezone.utc)
    if now is None:
        raise ValueError("now_iso must read YYYY-MM-DDTHH:MM:SSZ, not %r" % now_iso)
    rows = []
    for pr in prs:
        number = int(pr["number"])
        head = _text(pr.get("headRefOid"))
        landed = is_landed(head, main_ref, cwd=cwd)
        idle = idle_days_of(pr, now)
        reason_listed = listed.get(number)
        klass = classify_pr(pr, landed, reason_listed, idle)
        draft = " (draft)" if pr.get("isDraft") else ""
        mergeable = _text(pr.get("mergeable")) or "unset"
        idle_text = "unknown" if idle is None else str(idle)
        if klass == "LANDED":
            reason = "Landed: head %s is on %s%s" % (head, main_ref, draft)
        elif klass == "SUPERSEDED":
            reason = _text(reason_listed) + draft
        elif klass == "NO-DATA":
            why = "head %s not provable against %s (fetch first)" % (head or "absent", main_ref) \
                if landed is None else "updatedAt %r unparseable or in the future" % pr.get("updatedAt")
            reason = "NO-DATA: %s%s" % (why, draft)
        elif reason_listed is not None:
            reason = ("uncorroborated listing: idle %s days, mergeable %s; listed reason: %s%s"
                      % (idle_text, mergeable, _text(reason_listed), draft))
        else:
            reason = "idle %s days, mergeable %s, base %s%s" % (
                idle_text, mergeable, _text(pr.get("baseRefName")) or "unset", draft)
        rows.append({"number": str(number), "class": klass, "reason": reason,
                     "idle_days": idle_text, "mergeable": mergeable, "head": head,
                     "draft": "yes" if pr.get("isDraft") else "no"})
    return rows


def render_park_list(rows):
    # type: (List[Dict[str, str]]) -> str
    """`<number> <reason>` lines for LANDED and SUPERSEDED rows only, the
    exact input shape of scripts/close_superseded.sh. One header comment."""
    lines = [PARK_HEADER]
    for row in rows:
        if row["class"] in ("LANDED", "SUPERSEDED"):
            lines.append("%s %s" % (row["number"], _text(row["reason"])))
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--repo", default=REPO)
    ap.add_argument("--main-ref", default="hub/main")
    ap.add_argument("--close-list", default=None, help="the owner's close list (NO-DATA when unreadable)")
    ap.add_argument("--out", default=PARK_LIST)
    ap.add_argument("--limit", type=int, default=LIST_LIMIT)
    ap.add_argument("--now", default="", help="YYYY-MM-DDTHH:MM:SSZ (default: the clock)")
    args = ap.parse_args(argv)

    prs, problem = fetch_open_prs(args.repo, args.limit)
    if prs is None:
        print("NO-DATA: %s" % problem)
        return 2
    try:
        rows = triage(prs, {}, args.main_ref, args.now, close_list_path=args.close_list)
        listed = read_close_list(args.close_list) if args.close_list else {}
    except (OSError, ValueError) as exc:
        print("NO-DATA: close list %s: %s" % (args.close_list, exc))
        return 2
    if len(prs) >= args.limit:
        print("WARNING: %d pull requests read with --limit %d, the list may be truncated" % (len(prs), args.limit))
    open_numbers = {int(r["number"]) for r in rows}
    for number in sorted(listed):
        if number not in open_numbers:
            print("SKIP #%d: listed for close but not in the open list (already closed or merged)" % number)
    for row in rows:
        print("#%s %s: %s" % (row["number"], row["class"], row["reason"]))
    counts = {k: sum(1 for r in rows if r["class"] == k) for k in CLASSES}
    print("open %d: %s" % (len(rows), " ".join("%s=%d" % (k, counts[k]) for k in CLASSES)))
    text = render_park_list(rows)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("park list: %s (%d line(s))" % (args.out, len(text.splitlines()) - 1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
