#!/usr/bin/env python3
"""reproduce_export: prove a released public tag was generated from a pinned
hub revision by the exporter, byte for byte.

Red-team item 3 / section 5, and the infra persona's hardest question:
"which signed release archive rebuilds byte-for-byte on a clean machine". The
release_invariant tool proves the version STRINGS line up; this one proves the
CONTENT does: it regenerates the allowlisted export bytes from a named hub
revision and compares each file, byte for byte, against what the tag actually
carries.

Scope, stated honestly: the exporter APPENDS allowlisted files onto the public
repository's existing history, so the tag's whole tree is (prior public tree)
plus (allowlisted overwrites). The reproducible claim is therefore about the
EXPORTED CONTENT: every allowlisted path in the tag equals the bytes the
exporter generates from the pinned source. A file the tag carries that the
allowlist does not name is pre-existing public history, out of scope here and
reported as such, never counted as a mismatch.

  --source-rev REV   the hub revision the release was cut from (default HEAD)
  --tag TAG          the public tag to compare against (e.g. v0.9.7)
  --public CHECKOUT  a local checkout of the public repo that has the tag

EXITS: 0 every allowlisted path reproduces byte for byte; 1 any allowlisted
path the tag carries differs from the regenerated bytes (a broken chain);
2 NO-DATA (the source rev, the allowlist, or the tag tree could not be read).

Python 3, standard library only.
"""
import argparse
import hashlib
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import export_public as EP  # noqa: E402

PUBLIC_CHECKOUT = os.path.expanduser("~/Brother")


def _run(cmd, cwd=None):
    return subprocess.run(cmd, cwd=cwd, capture_output=True)


def _sha(data):
    return hashlib.sha256(data).hexdigest()


def source_tree(source_rev, root=EP.ROOT):
    """Check out `source_rev` of the hub into a temp dir and return its path.
    None when the revision cannot be materialised."""
    tmp = tempfile.mkdtemp(prefix="reproduce-src-")
    arc = _run(["git", "-C", root, "archive", source_rev])
    if arc.returncode != 0:
        return None
    extract = subprocess.run(["tar", "-x", "-C", tmp], input=arc.stdout)
    if extract.returncode != 0:
        return None
    return tmp


def tag_file_bytes(tag, relpath, public=PUBLIC_CHECKOUT):
    """The bytes the tag carries for one path, or None when absent/unreadable."""
    proc = _run(["git", "-C", public, "show",
                 "%s:%s" % (tag, relpath.replace(os.sep, "/"))])
    if proc.returncode != 0:
        return None
    return proc.stdout


def apply_release_stamp(export_dir, tag, source_rev):
    """A commit cannot contain its own hash: export_public.py stamps
    docs/releases/<version>.md with the hub HEAD taken AFTER --source-rev
    was cut, so the pre-stamp tree checked out from --source-rev never
    carries the stamp the tag does, and comparing it raw always mismatches
    on that one file. This reproducer holds the exact two inputs the stamp
    is made from (source_rev, tag), so it applies EP's own
    stamp_source_revision here instead of comparing the unstamped file.
    stamp_source_revision is a no-op on a record that already carries the
    header, and it embeds `source_rev` verbatim, so a release genuinely
    stamped with a DIFFERENT revision than --source-rev names still
    surfaces as a mismatch below: this never rewrites the tag's claim to
    match, only reproduces what --source-rev's own stamp would say."""
    version = tag.lstrip("v")
    notes_path = os.path.join(export_dir, "docs", "releases",
                               "%s.md" % version)
    if os.path.isfile(notes_path):
        EP.stamp_source_revision(notes_path, version, source_rev)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--source-rev", default="HEAD")
    ap.add_argument("--tag", required=True)
    ap.add_argument("--public", default=PUBLIC_CHECKOUT)
    ap.add_argument("--allowlist", default=None)
    args = ap.parse_args(argv)

    allowlist = EP.load_allowlist(args.allowlist)
    if allowlist is None:
        print("NO-DATA: no allowlist; nothing to reproduce")
        return 2

    src = source_tree(args.source_rev)
    if src is None:
        print("NO-DATA: could not materialise source revision %s"
              % args.source_rev)
        return 2

    if not os.path.exists(os.path.join(args.public, ".git")):
        print("NO-DATA: no public checkout at %s to read tag %s from"
              % (args.public, args.tag))
        return 2

    export_dir = tempfile.mkdtemp(prefix="reproduce-export-")
    copied = EP.build_export_tree(export_dir, allowlist, root=src)
    if not copied:
        print("NO-DATA: the allowlist copied nothing from %s"
              % args.source_rev)
        return 2
    apply_release_stamp(export_dir, args.tag, args.source_rev)

    reproduced, mismatched, out_of_scope_missing = [], [], []
    for base, _dirs, files in os.walk(export_dir):
        for fn in files:
            full = os.path.join(base, fn)
            rel = os.path.relpath(full, export_dir)
            with open(full, "rb") as fh:
                gen = fh.read()
            want = tag_file_bytes(args.tag, rel, args.public)
            if want is None:
                # the exporter generated a path the tag does not carry: it
                # was added to the hub after the tag was cut. Not a mismatch,
                # named so the count is honest.
                out_of_scope_missing.append(rel)
            elif _sha(gen) == _sha(want):
                reproduced.append(rel)
            else:
                mismatched.append(rel)

    print("reproduce-export: %d allowlisted file(s) regenerated from %s"
          % (len(reproduced) + len(mismatched) + len(out_of_scope_missing),
             args.source_rev))
    print("  reproduced byte-for-byte against %s: %d" % (args.tag,
                                                         len(reproduced)))
    if out_of_scope_missing:
        print("  generated but absent from %s (added after the tag, out of "
              "scope): %d" % (args.tag, len(out_of_scope_missing)))
    if mismatched:
        for rel in mismatched:
            print("MISMATCH: %s differs between the regenerated export and %s"
                  % (rel, args.tag))
        print("reproduce-export: the export is NOT reproducible; %d file(s) "
              "differ" % len(mismatched))
        return 1
    if not reproduced:
        print("NO-DATA: no allowlisted file could be compared against %s "
              "(is the tag on this checkout?)" % args.tag)
        return 2
    print("reproduce-export: every comparable allowlisted file rebuilds "
          "byte-for-byte from %s into %s" % (args.source_rev, args.tag))
    return 0


if __name__ == "__main__":
    sys.exit(main())
