#!/usr/bin/env python3
"""reproduce_export: prove a released public tag was generated from a pinned
hub revision by the exporter, byte for byte.

Red-team item 3 / section 5, and the infra persona's hardest question:
"which signed release archive rebuilds byte-for-byte on a clean machine". The
release_invariant tool proves the version STRINGS line up; this one proves the
CONTENT does: it regenerates the allowlisted export bytes from a named hub
revision and compares each file, byte for byte, against what the tag actually
carries.

Scope, stated honestly: the exporter APPENDS allowlisted files onto the public
repository's existing history, so the tag's whole tree is (prior public tree)
plus (allowlisted overwrites). The reproducible claim is therefore about the
EXPORTED CONTENT: every allowlisted path in the tag equals the bytes the
exporter generates from the pinned source. A file the tag carries that the
allowlist does not name is pre-existing public history, out of scope here and
reported as such, never counted as a mismatch.

  --source-rev REV   the hub revision the release was cut from (default HEAD)
  --tag TAG          the public tag to compare against (e.g. v0.9.7)
  --public CHECKOUT  a local checkout of the public repo that has the tag

EXITS: 0 every allowlisted path reproduces byte for byte; 1 any allowlisted
path the tag carries differs from the regenerated bytes (a broken chain);
2 NO-DATA (the source rev, the allowlist, or the tag tree could not be read).

E80, THE MODE THAT RUNS FROM THE OUTSIDE (--verify-tree). Everything above
needs the PRIVATE HUB: --source-rev names a hub commit, and a clone of the
public repository cannot resolve it (`git cat-file` exits 128 on it), so the
release-integrity persona rebuilding the release from source could not even
start. The release note also stamped that same unresolvable hub commit as its
headline claim.

--verify-tree is the half a stranger CAN run, from a clone at the tag, with no
private access and no network:

    git checkout v1.0.1
    python3 scripts/reproduce_export.py --verify-tree --tag v1.0.1

It reads docs/releases/<version>.export-manifest.txt, which the release note
generator writes and the tag ships: one "<sha256>  <path>" line per exported
file. It checks the manifest's own digest against the digest the release note
states, then re-hashes every file the manifest names out of the tag itself.
PASS only when both hold; FAIL naming each file that does not; NO-DATA when
the manifest or the stated digest is not there to read. The hub commit is
still recorded in the note, labelled as private, and nothing here depends on
it.

The digest cannot cover docs/releases/: the note that carries a digest cannot
also be hashed by it. That exclusion is stated in the note and here, never
left for a reader to discover.

Python 3, standard library only.
"""
import argparse
import atexit
import hashlib
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import export_public as EP  # noqa: E402

PUBLIC_CHECKOUT = os.path.expanduser("~/Brother")


def _run(cmd, cwd=None):
    return subprocess.run(cmd, cwd=cwd, capture_output=True)


def _sha(data):
    return hashlib.sha256(data).hexdigest()


def source_tree(source_rev, root=EP.ROOT):
    """Check out `source_rev` of the hub into a temp dir and return its path.
    None when the revision cannot be materialised."""
    # A detached worktree, not `git archive`: the exporter selects files by
    # asking git what the tree tracks (export_public._tracked_files_under),
    # and an extracted archive has no index to ask, so it copied nothing and
    # every reproduction read NO-DATA (found on the v1.0.1 proof, 2026-09-03).
    tmp = tempfile.mkdtemp(prefix="reproduce-src-")
    os.rmdir(tmp)
    add = _run(["git", "-C", root, "worktree", "add", "--detach", tmp,
                source_rev])
    if add.returncode != 0:
        return None
    atexit.register(lambda: _run(["git", "-C", root, "worktree", "remove",
                                  "--force", tmp]))
    return tmp


def tag_file_bytes(tag, relpath, public=PUBLIC_CHECKOUT):
    """The bytes the tag carries for one path, or None when absent/unreadable."""
    proc = _run(["git", "-C", public, "show",
                 "%s:%s" % (tag, relpath.replace(os.sep, "/"))])
    if proc.returncode != 0:
        return None
    return proc.stdout


#: The one prefix the export manifest cannot cover. The release note carries
#: the manifest's digest, so a digest computed over the note would have to
#: contain its own hash. Excluding the whole directory (not just the one
#: note) also keeps the digest stable when an OLDER note is re-stamped, which
#: export_public.stamp_source_revision is allowed to do at any later cut.
MANIFEST_EXCLUDED_PREFIX = "docs/releases/"

#: The sentence release_note_from_tree.py writes and this reads back. Both
#: sides use this one pattern, so the note's wording and the reproduction can
#: never drift into disagreeing about where the digest is.
NOTE_DIGEST_RE = re.compile(r"Export manifest digest `([0-9a-f]{64})`")


def manifest_path_for(version):
    """The path, inside the export, of the manifest for `version`. Under
    docs/releases/ on purpose: that prefix is the one the digest excludes,
    so the manifest never has to hash itself either."""
    return "docs/releases/%s.export-manifest.txt" % version


def manifest_text(entries):
    """entries: iterable of (relpath, bytes). One "<sha256>  <path>" line per
    covered file, sorted by path, newline terminated. Pure: every case in
    scripts/test_reproduce_export.py feeds this literal pairs, no filesystem."""
    rows = []
    for rel, data in entries:
        rel = rel.replace(os.sep, "/")
        if rel.startswith(MANIFEST_EXCLUDED_PREFIX):
            continue
        rows.append((rel, _sha(data)))
    rows.sort()
    return "".join("%s  %s\n" % (sha, rel) for rel, sha in rows)


def manifest_from_dir(export_dir):
    """The manifest text for an export tree already built on disk. An
    unreadable file raises rather than being skipped: a manifest silently
    missing a file it should cover would be a quiet lie, and the caller
    turns the OSError into a named NO-DATA."""
    entries = []
    for base, dirs, files in os.walk(export_dir):
        if ".git" in dirs:
            dirs.remove(".git")
        for fn in files:
            full = os.path.join(base, fn)
            with open(full, "rb") as fh:
                entries.append((os.path.relpath(full, export_dir), fh.read()))
    return manifest_text(entries)


def manifest_digest(text):
    """The one number the release note states, so a reader checks the whole
    manifest with a single comparison before checking any file in it."""
    return _sha(text.encode("utf-8"))


def parse_manifest(text):
    """[(sha, path)] for a well formed manifest, None for anything else
    (including an empty one): a manifest this cannot parse is NO-DATA, never
    an empty list that would let a verification pass over zero files."""
    out = []
    for line in text.splitlines():
        if not line.strip():
            continue
        parts = line.split("  ", 1)
        if len(parts) != 2 or not re.fullmatch(r"[0-9a-f]{64}", parts[0]):
            return None
        out.append((parts[0], parts[1]))
    return out or None


def _tag_text(tag, relpath, public):
    """One tag-carried file decoded as UTF-8 text, or None when the tag does
    not carry it or it is not text."""
    data = tag_file_bytes(tag, relpath, public)
    if data is None:
        return None
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError:  # sbe: allow-silent reader-only: None IS this function's documented answer for a tag entry that is not UTF-8 text, and every caller checks for it
        return None


def verify_tree(tag, public, expect=None):
    """The public-clone half of the reproduction: recompute the release's
    export manifest out of what the TAG itself carries, needing nothing from
    the private hub. Returns (exit_code, lines) with the same three verdicts
    this estate uses everywhere: 0 PASS, 1 FAIL, 2 NO-DATA."""
    version = tag.lstrip("v")
    rel_manifest = manifest_path_for(version)
    mtext = _tag_text(tag, rel_manifest, public)
    if mtext is None:
        return 2, ["NO-DATA: %s carries no %s, so there is no manifest to "
                   "recompute" % (tag, rel_manifest)]
    if expect is None:
        note = _tag_text(tag, "docs/releases/%s.md" % version, public)
        m = NOTE_DIGEST_RE.search(note) if note else None
        if m is None:
            return 2, ["NO-DATA: no --expect given and %s's own release note "
                       "states no export manifest digest to check against"
                       % tag]
        expect = m.group(1)
    got = manifest_digest(mtext)
    if got != expect:
        return 1, ["FAIL: %s in %s digests to %s, but the release note claims "
                   "%s; the manifest and the note disagree, so neither can be "
                   "trusted about the files" % (rel_manifest, tag, got, expect)]
    entries = parse_manifest(mtext)
    if entries is None:
        return 2, ["NO-DATA: %s is not in the '<sha256>  <path>' shape this "
                   "reproduction reads" % rel_manifest]
    lines, bad = [], 0
    for want_sha, rel in entries:
        data = tag_file_bytes(tag, rel, public)
        if data is None:
            lines.append("MISSING: %s is named in %s but %s does not carry it"
                         % (rel, rel_manifest, tag))
            bad += 1
        elif _sha(data) != want_sha:
            lines.append("MISMATCH: %s in %s does not hash to the value %s "
                         "names for it" % (rel, tag, rel_manifest))
            bad += 1
    if bad:
        lines.append("FAIL: %d of %d file(s) named in %s do not match what %s "
                     "ships" % (bad, len(entries), rel_manifest, tag))
        return 1, lines
    lines.append("PASS: %d exported file(s) in %s hash exactly to %s, whose "
                 "own digest %s is the one the release note states. Files "
                 "under %s are outside this digest by design."
                 % (len(entries), tag, rel_manifest, got,
                    MANIFEST_EXCLUDED_PREFIX))
    return 0, lines


def apply_release_stamp(export_dir, tag, source_rev):
    """A commit cannot contain its own hash: export_public.py stamps
    docs/releases/<version>.md with the hub HEAD taken AFTER --source-rev
    was cut, so the pre-stamp tree checked out from --source-rev never
    carries the stamp the tag does, and comparing it raw always mismatches
    on that one file. This reproducer holds the exact two inputs the stamp
    is made from (source_rev, tag), so it applies EP's own
    stamp_source_revision here instead of comparing the unstamped file.
    stamp_source_revision is a no-op on a record that already carries the
    header, and it embeds `source_rev` verbatim, so a release genuinely
    stamped with a DIFFERENT revision than --source-rev names still
    surfaces as a mismatch below: this never rewrites the tag's claim to
    match, only reproduces what --source-rev's own stamp would say."""
    version = tag.lstrip("v")
    notes_path = os.path.join(export_dir, "docs", "releases",
                               "%s.md" % version)
    if os.path.isfile(notes_path):
        EP.stamp_source_revision(notes_path, version, source_rev)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--source-rev", default="HEAD")
    ap.add_argument("--tag", required=True)
    ap.add_argument("--public", default=None,
                    help="checkout holding the tag (default: this checkout "
                         "under --verify-tree, %s otherwise)" % PUBLIC_CHECKOUT)
    ap.add_argument("--allowlist", default=None)
    ap.add_argument("--verify-tree", action="store_true",
                    help="the public-clone mode: check the tag against the "
                         "export manifest it ships, needing no hub access")
    ap.add_argument("--expect", default=None,
                    help="--verify-tree: the manifest digest to require "
                         "(default: the one the tag's own release note states)")
    args = ap.parse_args(argv)

    if args.verify_tree:
        # Default to THIS checkout, not ~/Brother: under --verify-tree the
        # script is running from inside the clone being verified, which is
        # the whole point of the mode.
        public = args.public or EP.ROOT
        code, lines = verify_tree(args.tag, public, args.expect)
        for line in lines:
            print(line)
        return code

    public = args.public or PUBLIC_CHECKOUT
    allowlist = EP.load_allowlist(args.allowlist)
    if allowlist is None:
        print("NO-DATA: no allowlist; nothing to reproduce")
        return 2

    src = source_tree(args.source_rev)
    if src is None:
        print("NO-DATA: could not materialise source revision %s"
              % args.source_rev)
        return 2

    if not os.path.exists(os.path.join(public, ".git")):
        print("NO-DATA: no public checkout at %s to read tag %s from"
              % (public, args.tag))
        return 2

    export_dir = tempfile.mkdtemp(prefix="reproduce-export-")
    copied = EP.build_export_tree(export_dir, allowlist, root=src)
    if not copied:
        print("NO-DATA: the allowlist copied nothing from %s"
              % args.source_rev)
        return 2
    apply_release_stamp(export_dir, args.tag, args.source_rev)

    reproduced, mismatched, out_of_scope_missing = [], [], []
    for base, _dirs, files in os.walk(export_dir):
        for fn in files:
            full = os.path.join(base, fn)
            rel = os.path.relpath(full, export_dir)
            with open(full, "rb") as fh:
                gen = fh.read()
            want = tag_file_bytes(args.tag, rel, public)
            if want is None:
                # the exporter generated a path the tag does not carry: it
                # was added to the hub after the tag was cut. Not a mismatch,
                # named so the count is honest.
                out_of_scope_missing.append(rel)
            elif _sha(gen) == _sha(want):
                reproduced.append(rel)
            else:
                mismatched.append(rel)

    print("reproduce-export: %d allowlisted file(s) regenerated from %s"
          % (len(reproduced) + len(mismatched) + len(out_of_scope_missing),
             args.source_rev))
    print("  reproduced byte-for-byte against %s: %d" % (args.tag,
                                                         len(reproduced)))
    if out_of_scope_missing:
        print("  generated but absent from %s (added after the tag, out of "
              "scope): %d" % (args.tag, len(out_of_scope_missing)))
    if mismatched:
        for rel in mismatched:
            print("MISMATCH: %s differs between the regenerated export and %s"
                  % (rel, args.tag))
        print("reproduce-export: the export is NOT reproducible; %d file(s) "
              "differ" % len(mismatched))
        return 1
    if not reproduced:
        print("NO-DATA: no allowlisted file could be compared against %s "
              "(is the tag on this checkout?)" % args.tag)
        return 2
    print("reproduce-export: every comparable allowlisted file rebuilds "
          "byte-for-byte from %s into %s" % (args.source_rev, args.tag))
    return 0


if __name__ == "__main__":
    sys.exit(main())
