#!/usr/bin/env python3
"""QS1.c: the shipped session start block holds its byte budget (docs/plan/specs/QS1.md).

WHAT IS PINNED. Every SessionStart command the shipped bundle registers (bundle/hooks/hooks.json, generated by
scripts/bundle_runtime.py) runs exactly as Claude Code would run it: through runtime/hooks/hook_guard.py, with
CLAUDE_PLUGIN_ROOT at the bundle and the hook payload on stdin, in a fake HOME holding a consented BrotherMode config,
from an established git project. With no switch their stdout together stays at or under QUIET_START_BUDGET bytes;
with BROTHER_VERBOSE_START=1 the same commands print more; the count of SessionStart commands is unchanged by QS1;
and the bundle's copies equal their product sources (bundle_runtime.py --check).

WHY A BUDGET AND NOT ZERO. The setup line before consent, the first run welcome, an update notice and the recovery
hint after a compaction are allowed to print. The fixture has none of them, so it measures the routine block, which
QS1 took from 5,820 bytes (bm_sessionstart.py alone, measured 2026-10-10) to nothing. The budget is raised only by a
reviewed change that says why.

Python 3.9 and 3.13, standard library only, no network; nothing touches the real ~/.claude, ~/.brotherme or a vault.
"""
import io
import json
import os
import shlex
import shutil
import subprocess
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
BUNDLE = os.path.join(REPO, "bundle")
HOOKS = os.path.join(BUNDLE, "hooks", "hooks.json")
QUIET_START_BUDGET = 512
SESSION_START_COMMANDS = 4


def session_start_commands(hooks_path):
    """The SessionStart command strings the bundle registers, in file order."""
    with io.open(hooks_path, encoding="utf-8") as fh:
        doc = json.load(fh)
    return [h["command"] for group in doc["hooks"].get("SessionStart", []) for h in group.get("hooks", [])
            if h.get("type") == "command"]


def quiet_start_bytes(bundle_root, home, project, extra_env=None):
    """{command: stdout bytes} for every SessionStart command, run as the host runs it."""
    env = {"HOME": home, "PATH": os.environ.get("PATH", "/usr/bin:/bin"), "PYTHONDONTWRITEBYTECODE": "1",
           "CLAUDE_PLUGIN_ROOT": os.path.realpath(bundle_root)}
    env.update(extra_env or {})
    out = {}
    payload = json.dumps({"session_id": "test-footprint", "cwd": project, "hook_event_name": "SessionStart",
                          "source": "startup"}).encode("utf-8")
    for command in session_start_commands(os.path.join(bundle_root, "hooks", "hooks.json")):
        argv = [a.replace("${CLAUDE_PLUGIN_ROOT}", env["CLAUDE_PLUGIN_ROOT"]) for a in shlex.split(command)]
        if argv and argv[0] == "python3":
            argv[0] = sys.executable
        r = subprocess.run(argv, cwd=project, env=env, input=payload, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=300)
        if r.returncode != 0:
            raise AssertionError("%s exited %d: %s" % (command, r.returncode,
                                                      r.stderr.decode("utf-8", "replace")[-400:]))
        out[command] = len(r.stdout)
    return out


class StartBlockBudget(unittest.TestCase):

    def setUp(self):
        self.tmp = tempfile.mkdtemp(prefix="test-footprint-budget-")
        self.addCleanup(shutil.rmtree, self.tmp, True)
        self.home = os.path.join(self.tmp, "home")
        self.project = os.path.join(self.tmp, "project")
        os.makedirs(os.path.join(self.home, ".brotherme"))
        os.makedirs(os.path.join(self.project, "docs", "plan"))
        with io.open(os.path.join(self.home, ".brotherme", "config.json"), "w", encoding="utf-8") as fh:
            json.dump({"setup_complete": True, "vault_path": os.path.join(self.home, "Vault"),
                       "privacy_notice_version": "2026-08-01", "installation_mode": "plugin",
                       "security_mode": "standard"}, fh)
        with io.open(os.path.join(self.project, "docs", "plan", "QUEUE.json"), "w", encoding="utf-8") as fh:
            fh.write("{}")
        subprocess.run(["git", "init", "-q", self.project], check=True, stdout=subprocess.DEVNULL,
                       stderr=subprocess.DEVNULL)

    def test_the_session_start_command_count_is_unchanged(self):
        self.assertEqual(len(session_start_commands(HOOKS)), SESSION_START_COMMANDS)

    def test_the_quiet_start_block_holds_its_budget(self):
        sizes = quiet_start_bytes(BUNDLE, self.home, self.project)
        self.assertEqual(len(sizes), SESSION_START_COMMANDS)
        self.assertLessEqual(sum(sizes.values()), QUIET_START_BUDGET,
                             "the shipped quiet start printed %d bytes: %s" % (sum(sizes.values()), sizes))

    def test_the_switch_brings_the_routine_block_back(self):
        quiet = sum(quiet_start_bytes(BUNDLE, self.home, self.project).values())
        verbose = sum(quiet_start_bytes(BUNDLE, self.home, self.project, {"BROTHER_VERBOSE_START": "1"}).values())
        self.assertGreater(verbose, quiet)

    def test_the_bundle_carries_the_product_sources(self):
        r = subprocess.run([sys.executable, os.path.join(HERE, "bundle_runtime.py"), "--check"], cwd=REPO,
                           stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=300)
        self.assertEqual(r.returncode, 0, r.stdout.decode("utf-8", "replace")[-600:])


if __name__ == "__main__":
    unittest.main(verbosity=1)
