"""What the living system record must keep true.

The one property that distinguishes this from the fifty designs it replaces is
that it goes RED when the code moves. Everything else about it is presentation.
So the tests here are mostly about staleness and about refusing to hide the
undocumented and unproven corners.
"""
import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import system_doc as S  # noqa: E402


def module(dirpath, name, doc=None):
    p = os.path.join(dirpath, name + ".py")
    with open(p, "w", encoding="utf-8") as fh:
        fh.write(('"""%s"""\n' % doc) if doc else "x = 1\n")
    return p


class ItGoesRedWhenTheCodeMoves(unittest.TestCase):
    """The whole point. A design that cannot notice it is wrong is design
    fifty one."""

    def setUp(self):
        self.d = tempfile.mkdtemp()
        self.out = os.path.join(self.d, "SYSTEM.md")

    def test_a_fresh_record_passes_its_own_check(self):
        S.main(["--out", self.out])
        self.assertEqual(S.main(["--check", "--out", self.out]), 0)

    def test_a_missing_record_fails_rather_than_passing_quietly(self):
        self.assertEqual(S.main(["--check", "--out", self.out]), 1)

    def test_an_edited_record_fails(self):
        S.main(["--out", self.out])
        with open(self.out, "a", encoding="utf-8") as fh:
            fh.write("\nsomebody edited this by hand\n")
        self.assertEqual(S.main(["--check", "--out", self.out]), 1)


class ItDescribesWhatExistsNotWhatWasIntended(unittest.TestCase):
    def setUp(self):
        self.d = tempfile.mkdtemp()

    def test_the_purpose_is_the_authors_own_first_line(self):
        p = module(self.d, "thing", "thing: does the one thing it says.")
        self.assertEqual(S.purpose(p), "does the one thing it says.")

    def test_a_module_with_no_docstring_returns_None(self):
        self.assertIsNone(S.purpose(module(self.d, "bare")))

    def test_an_unparseable_file_returns_None_rather_than_raising(self):
        p = os.path.join(self.d, "broken.py")
        with open(p, "w", encoding="utf-8") as fh:
            fh.write("def (:\n")
        self.assertIsNone(S.purpose(p))

    def test_test_modules_are_not_listed_as_parts(self):
        module(self.d, "real", "real: a part.")
        module(self.d, "test_real", "tests for the part.")
        names = [r["module"] for r in S.parts(self.d)]
        self.assertIn("real", names)
        self.assertNotIn("test_real", names)


class ItRefusesToHideTheGaps(unittest.TestCase):
    """A system record that omits its undocumented and unproven corners looks
    complete and is not, which is worse than having none."""

    def test_an_undocumented_part_is_shown_as_NO_DATA(self):
        rows = [{"module": "bare", "purpose": None, "proven_by": [], "has_tests": False}]
        body = S.render(rows, [])
        self.assertIn("bare", body)
        self.assertIn(S.NODATA, body)

    def test_a_part_nothing_proves_says_so_in_its_own_row(self):
        rows = [{"module": "lonely", "purpose": "does a thing", "proven_by": [],
                 "has_tests": False}]
        self.assertIn("nothing in the battery runs it", S.render(rows, []))

    def test_the_counts_separate_documented_from_proven(self):
        rows = [{"module": "a", "purpose": "x", "proven_by": ["c"], "has_tests": True},
                {"module": "b", "purpose": "y", "proven_by": [], "has_tests": False}]
        body = S.render(rows, [("c", "cmd")])
        self.assertIn("| Parts | 2 |", body)
        self.assertIn("| Parts with a suite wired into the battery | 1 |", body)

    def test_it_says_not_to_edit_by_hand(self):
        self.assertIn("Do not edit this file by hand", S.render([], []))


class NoDataIsNeverAPass(unittest.TestCase):
    def test_an_unreadable_battery_is_NO_DATA_not_an_empty_document(self):
        real = S.BATTERY
        S.BATTERY = "/no/such/check_all.sh"
        try:
            self.assertIsNone(S.build())
            self.assertEqual(S.main(["--out", os.path.join(tempfile.mkdtemp(), "x.md")]), 2)
        finally:
            S.BATTERY = real


class TheRealRecordIsCurrent(unittest.TestCase):
    """This is the check that runs in the battery. It fails the day somebody
    adds a script and does not regenerate."""

    def test_the_shipped_SYSTEM_md_still_describes_this_code(self):
        self.assertEqual(S.main(["--check"]), 0)

    def test_it_describes_a_real_number_of_parts(self):
        rows = S.parts()
        self.assertGreater(len(rows), 10)
        self.assertTrue(all(r["module"] for r in rows))


class TransitiveCreditIsEarnedFromTheRunnersSource(unittest.TestCase):
    """A runner the battery names invokes sibling scripts, and those siblings used to
    be credited to nobody: eleven capability-area scripts printed "NO-DATA, nothing in
    the battery runs it" while a live run of their runner passed all eleven. The
    generated map and the harness disagreed and nothing in the tree could adjudicate.

    Both directions are pinned here, because the failure this could introduce is worse
    than the one it fixes: crediting a module the runner merely MENTIONS would turn the
    map from understating coverage into overstating it, and an overstated map is the
    thing NO-DATA exists to prevent."""

    def _fixture(self, runner_src, siblings, battery_line):
        d = tempfile.mkdtemp(prefix="sysdoc-credit-")
        scripts = os.path.join(d, "scripts")
        os.makedirs(scripts)
        with open(os.path.join(scripts, "runner.py"), "w", encoding="utf-8") as fh:
            fh.write('"""runner: a fixture runner."""\n' + runner_src)
        for name in siblings:
            with open(os.path.join(scripts, name), "w", encoding="utf-8") as fh:
                fh.write('"""%s: a fixture sibling."""\n' % name[:-3])
        battery = os.path.join(scripts, "check_all.sh")
        with open(battery, "w", encoding="utf-8") as fh:
            fh.write(battery_line + "\n")
        return scripts, battery

    def _credited(self, scripts, battery, module):
        real = S.BATTERY
        S.BATTERY = battery
        try:
            rows = S.parts(scripts_dir=scripts)
        finally:
            S.BATTERY = real
        for r in rows:
            if r["module"] == module:
                return r["proven_by"]
        self.fail("no row for %r" % module)

    def test_a_sibling_the_runner_builds_by_name_is_credited(self):
        scripts, battery = self._fixture(
            'script = "area_{}.py".format(n)\n',
            ["area_1.py", "area_2.py"],
            'run_check "areas" python3 scripts/runner.py')
        self.assertEqual(self._credited(scripts, battery, "area_1"), ["areas"])
        self.assertEqual(self._credited(scripts, battery, "area_2"), ["areas"])

    def test_a_module_only_mentioned_in_prose_is_NOT_credited(self):
        scripts, battery = self._fixture(
            '# see area_1 for the older approach, which this replaces\n'
            'pass\n',
            ["area_1.py"],
            'run_check "areas" python3 scripts/runner.py')
        self.assertEqual(
            self._credited(scripts, battery, "area_1"), [],
            "a comment is not an invocation: crediting it would overstate coverage")


if __name__ == "__main__":
    unittest.main()
