#!/usr/bin/env python3
"""FX-09.5: with BROTHER_BRIEF_SCREEN=on the brief carries THE GRADER'S SCREEN, generated by grade_build.screen_rules
from the grader's own rules; unset or off, the brief is byte identical to today's; any other value refuses the brief.

WHY: 52 percent of one day's attempts (12 of 23 grades on 2026-09-29) were refused by the safety screen before any
test ran, for rules no brief ever stated. The screen text is generated, never retyped, so it cannot drift from what the
grader enforces. Drives build_brief.py as the loop does and reads the result through brief_check.main.
Run: python3 -B scripts/test_build_brief_screen.py"""
import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from test_build_brief_keeps_every_file import BriefTree, blocks  # noqa: E402
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "loop"))
import grade_build as G  # noqa: E402


def screen_block(brief):
    """The screen block: from its head to the first blank line."""
    at = brief.index(G.SCREEN_HEAD)
    end = brief.find("\n\n", at)
    return brief[at:end if end >= 0 else len(brief)]


class TheBriefCarriesTheGradersScreen(unittest.TestCase):
    def setUp(self):
        self.t = BriefTree(self)
        self.t.write("scripts/pure.py", "import json\n")
        self.t.write("scripts/spawner.py", "import subprocess\n")
        self.t.spec("Files: `scripts/pure.py` and `scripts/spawner.py` existing.\n")

    def test_unset_switch_is_off_and_the_brief_has_no_screen(self):
        r = self.t.build("unset.md")
        self.assertEqual(r.returncode, 0, r.stderr)
        r = self.t.build("off.md", BROTHER_BRIEF_SCREEN="off")
        self.assertEqual(r.returncode, 0, r.stderr)
        unset, off = self.t.read("unset.md"), self.t.read("off.md")
        self.assertNotIn(G.SCREEN_HEAD, unset)
        self.assertEqual(unset, off)

    def test_switch_on_adds_one_screen_block_that_brief_check_passes(self):
        r = self.t.build(BROTHER_BRIEF_SCREEN="on")
        self.assertEqual(r.returncode, 0, r.stderr)
        brief = self.t.read()
        self.assertEqual(brief.count(G.SCREEN_HEAD), 1)
        self.assertLess(brief.index(G.SCREEN_HEAD), brief.index("THE SPECIFICATION"))
        self.assertLess(brief.index(G.SCREEN_HEAD), brief.index("THE REAL FILES:"))
        block = screen_block(brief)
        cwd = os.getcwd()
        os.chdir(self.t.root)                          # the grader's own reading of this tree, as build_brief made it
        try:
            G._REPO_SAFE.clear()
            self.assertEqual(block, G.screen_rules(["scripts/pure.py", "scripts/spawner.py"]).rstrip("\n"))
        finally:
            G._REPO_SAFE.clear()
            os.chdir(cwd)
        for line in block.splitlines():
            self.assertFalse(line.startswith("===== FILE: "), line)
            self.assertFalse(line.startswith("THIS UNIT, FROM THE WBS"), line)
        self.assertIn("scripts/pure.py: importable", block)
        self.assertIn("scripts/spawner.py: NOT importable", block)
        self.assertEqual(blocks(brief), ["scripts/pure.py", "scripts/spawner.py"])
        code, out = self.t.gate()
        self.assertEqual(code, 0, out)

    def test_switch_on_changes_nothing_before_the_block(self):
        self.assertEqual(self.t.build("off.md").returncode, 0)
        self.assertEqual(self.t.build("on.md", BROTHER_BRIEF_SCREEN=" ON ").returncode, 0)
        off, on = self.t.read("off.md"), self.t.read("on.md")
        at = on.index(G.SCREEN_HEAD) - 1
        self.assertEqual(on[:at], off[:at])

    def test_an_unknown_switch_value_refuses_the_brief(self):
        r = self.t.build(BROTHER_BRIEF_SCREEN="yes")
        self.assertEqual(r.returncode, 2, r.stdout)
        self.assertIn("BROTHER_BRIEF_SCREEN", r.stderr)
        self.assertIn("NO-DATA", r.stderr)
        self.assertFalse(os.path.exists(os.path.join(self.t.root, "out.md")))

    def test_a_private_term_in_the_screen_refuses_the_brief(self):
        self.t.write("_home/.brothersbe-private-names", "subprocess\n")
        r = self.t.build(BROTHER_BRIEF_SCREEN="on")
        self.assertEqual(r.returncode, 2, r.stdout)
        self.assertIn("the screen block carries a private term", r.stderr)
        self.assertFalse(os.path.exists(os.path.join(self.t.root, "out.md")))

    def test_empty_home_fails_closed_both_ways(self):
        os.remove(os.path.join(self.t.home, ".brothersbe-private-names"))
        r = self.t.build()
        self.assertEqual(r.returncode, 0, r.stderr)
        brief = self.t.read()
        self.assertEqual(blocks(brief), ["scripts/pure.py", "scripts/spawner.py"])
        self.assertEqual(brief.count("[NOT SHOWN: this file carries a private term"), 2)
        os.remove(os.path.join(self.t.root, "out.md"))
        r = self.t.build(BROTHER_BRIEF_SCREEN="on")
        self.assertEqual(r.returncode, 2, r.stdout)
        self.assertFalse(os.path.exists(os.path.join(self.t.root, "out.md")))

    def test_the_screen_is_inside_the_planners_excerpt(self):
        # the planner reads brief[:30000] (unit_runner.py); a section as large as a real one must not push it out
        self.t.spec("Files: `scripts/pure.py` and `scripts/spawner.py` existing.\n" + ("A long paragraph. " * 40 + "\n") * 120)
        r = self.t.build(BROTHER_BRIEF_SCREEN="on")
        self.assertEqual(r.returncode, 0, r.stderr)
        brief = self.t.read()
        self.assertLess(brief.index(G.SCREEN_HEAD) + len(screen_block(brief)), 30000)


if __name__ == "__main__":
    unittest.main()
