"""L5e.4 audit doc assembly.

build_audit_doc, beside the other generated-document helpers in
scripts/system_doc.py, assembles the L5e documentation accuracy audit
document from section fragments. This suite asserts what the specification
says that document must carry: one section for SYSTEM.md accuracy, one for
PARITY-MATRIX accuracy, one for README install accuracy, and one score
table with one row per checked area.

Every hostile or missing input raises ValueError, never a raw interpreter
exception. A wrong type, an empty section list, a blank or headingless
fragment, a duplicate heading, an unclosed code fence, a stale document
that omits a required section, and a score section with no score table all
block rather than pass.

Done check: python3 -B scripts/test_l5e_4_audit_doc_assembly.py
"""

import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import system_doc as S  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUDIT_DOC_PATH = os.path.join(
    REPO_ROOT, "docs", "architecture", "L5E-DOCS-ACCURACY-AUDIT.md")

SYSTEM_FRAGMENT = (
    "## SYSTEM.md accuracy\n\n"
    "SYSTEM.md is regenerated by scripts/system_doc.py and diffed "
    "against the checked-in file."
)
PARITY_FRAGMENT = (
    "## PARITY-MATRIX accuracy\n\n"
    "Every MIGRATED and COVERED claim resolves to a real path or module "
    "and to a symbol contained there."
)
README_FRAGMENT = (
    "## README install accuracy\n\n"
    "Every install command in the README Installation fenced block runs "
    "in a fresh temp directory with a temp HOME."
)
SCORE_FRAGMENT = (
    "## Score\n\n"
    "| Area | Weight | Score |\n"
    "| --- | --- | --- |\n"
    "| SYSTEM.md accuracy | 0.34 | 10.0 |\n"
    "| PARITY-MATRIX accuracy | 0.33 | 10.0 |\n"
    "| README install accuracy | 0.33 | 10.0 |\n"
    "| Overall | 1.00 | 10.0 |"
)
FRAGMENTS = (SYSTEM_FRAGMENT, PARITY_FRAGMENT, README_FRAGMENT, SCORE_FRAGMENT)


def _split_sections(text):
    """Split a whole audit document into its level two fragments."""
    sections = []
    current = []
    for line in text.splitlines():
        if line.startswith("## "):
            if current:
                sections.append("\n".join(current))
            current = [line]
        elif current:
            current.append(line)
    if current:
        sections.append("\n".join(current))
    return sections


class AuditDocAssemblyTests(unittest.TestCase):

    @unittest.skipUnless(
        os.path.isfile(AUDIT_DOC_PATH),
        "docs/architecture/L5E-DOCS-ACCURACY-AUDIT.md is not in this tree",
    )
    def test_audit_doc_has_required_sections(self):
        """The checked-in audit doc assembles and carries every required
        heading plus its score table."""
        with open(AUDIT_DOC_PATH, "rb") as handle:
            raw = handle.read()
        self.assertTrue(raw, "the audit doc is empty")
        try:
            text = raw.decode("utf-8")
        except UnicodeDecodeError as exc:
            self.fail("the audit doc is not utf-8: %s" % exc)
        try:
            doc = S.build_audit_doc(_split_sections(text))
        except ValueError as exc:
            self.fail("the audit doc does not assemble: %s" % exc)
        self.assertTrue(doc.startswith(S.AUDIT_DOC_TITLE))
        for heading in S.AUDIT_DOC_REQUIRED_SECTIONS:
            self.assertIn("## " + heading, doc)
        self.assertIn("| Area | Weight | Score |", doc)
        self.assertIn("| --- | --- | --- |", doc)

    def test_build_audit_doc_from_fragments(self):
        doc = S.build_audit_doc(list(FRAGMENTS))
        self.assertTrue(doc.startswith(S.AUDIT_DOC_TITLE))
        for heading in S.AUDIT_DOC_REQUIRED_SECTIONS:
            self.assertIn("## " + heading, doc)
        self.assertIn("| Area | Weight | Score |", doc)

    def test_empty_section_list_is_refused(self):
        with self.assertRaises(ValueError):
            S.build_audit_doc([])

    def test_duplicate_headings_are_refused(self):
        with self.assertRaises(ValueError):
            S.build_audit_doc(list(FRAGMENTS) + [SYSTEM_FRAGMENT])

    def test_missing_section_is_refused(self):
        with self.assertRaises(ValueError):
            S.build_audit_doc(
                [PARITY_FRAGMENT, README_FRAGMENT, SCORE_FRAGMENT])

    def test_missing_score_table_is_refused(self):
        with self.assertRaises(ValueError):
            S.build_audit_doc([
                SYSTEM_FRAGMENT,
                PARITY_FRAGMENT,
                README_FRAGMENT,
                "## Score\n\nEvery area scored, in prose, with no table.",
            ])

    def test_score_table_missing_a_row_is_refused(self):
        bad_score = (
            "## Score\n\n"
            "| Area | Weight | Score |\n"
            "| --- | --- | --- |\n"
            "| SYSTEM.md accuracy | 0.34 | 10.0 |\n"
            "| PARITY-MATRIX accuracy | 0.33 | 10.0 |\n"
            "| Overall | 1.00 | 10.0 |"
        )
        with self.assertRaises(ValueError):
            S.build_audit_doc(
                [SYSTEM_FRAGMENT, PARITY_FRAGMENT, README_FRAGMENT, bad_score])

    def test_corrupt_markdown_is_refused(self):
        bad = SYSTEM_FRAGMENT + "\n\n```\nan unterminated code fence\n"
        with self.assertRaises(ValueError):
            S.build_audit_doc(
                [bad, PARITY_FRAGMENT, README_FRAGMENT, SCORE_FRAGMENT])

    def test_headingless_fragment_is_refused(self):
        with self.assertRaises(ValueError):
            S.build_audit_doc(list(FRAGMENTS) + ["prose with no heading"])

    def test_hostile_inputs_are_refused(self):
        hostile = (
            None,
            42,
            3.5,
            float("nan"),
            True,
            "a string",
            b"bytes",
            {"SYSTEM.md accuracy": 1},
            (SYSTEM_FRAGMENT,),
            frozenset([SYSTEM_FRAGMENT]),
        )
        for value in hostile:
            with self.assertRaises(ValueError):
                S.build_audit_doc(value)
        for value in ([None], [""], [b"bytes"], [123], [[]], [(1, 2)],
                      [float("nan")], [True]):
            with self.assertRaises(ValueError):
                S.build_audit_doc(value)


if __name__ == "__main__":
    unittest.main()
