#!/bin/sh
# Vault sweep: runs the vault's existing health checks in one pass and writes
# a dated report into the vault itself, so "clean by default" is a fact
# Obsidian shows rather than a claim only a session can see.
#
# Genuinely new code: this runner and the report writer. Every check it
# calls (graph link/enum validity, staleness, stable-ID coverage, authority
# declaration) already exists and is tested in products/brothermode/tools/;
# this script adds none of that logic itself, only sequences and reports it.
#
# Usage: scripts/vault_sweep.sh [VAULT_PATH]
# Exit: nonzero if any check failed. A tool that isn't found at TOOLS_DIR is
# reported as NO-DATA for that check, never silently skipped and never a
# hard failure of the whole sweep (same fail-open direction as the vault's
# own pre-commit gate, and for the same reason: a control here is not the
# thing it is protecting).

set -u

VAULT="${1:-$HOME/Documents/Kay Vault}"
TOOLS_DIR="${BM_TOOLS:-$(cd "$(dirname "$0")/.." && pwd)/products/brothermode/tools}"
REPORT="$VAULT/90-Views/Sweep-Latest.md"
TODAY="$(date +%Y-%m-%d)"
STAMP="$(date "+%Y-%m-%d %H:%M %Z")"

if [ ! -d "$VAULT" ]; then
  echo "vault_sweep: vault not found at $VAULT" >&2
  exit 2
fi

run_check() {
  # $1=label $2=script $3.. = args
  # Returns 0 PASS, 1+ FAIL, 3 NO-DATA (tool missing) -- three states, never
  # folded into one. NO-DATA is never a pass: an earlier version of this
  # script returned 0 for a missing tool, which let a sweep with every check
  # NO-DATA print "Verdict: clean" -- caught by adversarial review the same
  # session this script was written.
  label="$1"; script="$2"; shift 2
  path="$TOOLS_DIR/$script"
  if [ ! -f "$path" ]; then
    printf '%s: NO-DATA (tool not found at %s)\n' "$label" "$path"
    return 3
  fi
  raw="$(python3 "$path" "$@" --vault "$VAULT" 2>&1)"
  code=$?
  # Sanitize [[...]] out of captured tool output before it lands in the report,
  # AFTER capturing $code (a pipe's $? is the last command's, not python3's --
  # see 40-Failures/a-backtick-code-span-does-not-hide-a-wikilink-from-a-raw-regex-gate.md
  # for why the gate below cannot be fooled by Markdown escaping either): the
  # vault's link gate is a raw substring match, so a diagnostic line quoting an
  # example link would make this generated report fail its own gate every run.
  out="$(printf '%s' "$raw" | sed 's/\[\[/[ [/g; s/\]\]/] ]/g')"
  if [ "$code" -eq 0 ]; then
    printf '%s: PASS\n%s\n' "$label" "$out" | sed 's/^/  /'
  else
    printf '%s: FAIL (exit %s)\n%s\n' "$label" "$code" "$out" | sed 's/^/  /'
  fi
  return "$code"
}

TMP="$(mktemp)"
OVERALL=0
NODATA=0

{
  echo "---"
  echo "id: n-sweep-latest"
  echo "type: index"
  echo "authority: casual"
  echo "project: all"
  echo "created: $TODAY"
  echo "status: standing"
  echo "ingested_at: $TODAY"
  echo "verified_at: $TODAY"
  echo "tags: [sweep, health]"
  echo "verified-by: scripts/vault_sweep.sh, run $STAMP"
  echo "description: \"Latest automated vault sweep\""
  echo "---"
  echo ""
  echo "# Vault sweep, $STAMP"
  echo ""
  echo "Generated by scripts/vault_sweep.sh. Broader manual upkeep (duplicates,"
  echo "archiving, index refresh) stays [[99-System/Consolidation-Ritual|the Consolidation Ritual]];"
  echo "this sweep covers only what a script can check mechanically."
  echo ""
} > "$TMP"

note_result() {
  # $1 = this check's exit code, just observed
  if [ "$1" -eq 3 ]; then
    NODATA=$((NODATA + 1))
  elif [ "$1" -ne 0 ]; then
    OVERALL=1
  fi
}

run_check "Graph (links, enum validity)" bm_vault_graph.py check >> "$TMP" 2>&1; note_result "$?"
echo "" >> "$TMP"
run_check "Graph measure (orphans, connectivity)" bm_vault_graph.py measure >> "$TMP" 2>&1; note_result "$?"
echo "" >> "$TMP"
run_check "Staleness" bm_vault_staleness.py check >> "$TMP" 2>&1; note_result "$?"
echo "" >> "$TMP"
run_check "Stable IDs" bm_vault_ids.py check >> "$TMP" 2>&1; note_result "$?"
echo "" >> "$TMP"
run_check "Authority declarations" bm_vault_authority.py check >> "$TMP" 2>&1; note_result "$?"
echo "" >> "$TMP"

if [ "$OVERALL" -ne 0 ]; then
  echo "## Verdict: findings above need attention" >> "$TMP"
elif [ "$NODATA" -gt 0 ]; then
  echo "## Verdict: NO-DATA on $NODATA check(s) -- not a pass, see above for which tool is missing" >> "$TMP"
else
  echo "## Verdict: clean" >> "$TMP"
fi
echo "" >> "$TMP"
echo "## Links" >> "$TMP"
echo "- [[00-Home/Home|Home]]" >> "$TMP"
echo "- [[99-System/Consolidation-Ritual|Consolidation Ritual]] (the broader manual upkeep this sweep does not cover)" >> "$TMP"

mv "$TMP" "$REPORT"
if [ "$OVERALL" -ne 0 ]; then
  VERDICT_WORD="findings"
elif [ "$NODATA" -gt 0 ]; then
  VERDICT_WORD="no-data ($NODATA check(s))"
else
  VERDICT_WORD="clean"
fi
echo "vault_sweep: wrote $REPORT (verdict: $VERDICT_WORD)"
if [ "$OVERALL" -ne 0 ]; then
  exit 1
elif [ "$NODATA" -gt 0 ]; then
  exit 3
fi
exit 0
