#!/usr/bin/env python3
"""bm_vault_catalog: bakes generated index notes into the vault so every note has an
inbound link without hand curation.

  bake    (re)write 10-Projects/<slug>/Catalog.md for every project directory, and
          40-Failures/Failures-by-Symptom.md, from what is on disk right now
  check   exit 0 when every baked file matches a fresh bake, exit 2 and list what is
          stale otherwise, exit 3 NO-DATA when the vault has no project directories

Two consecutive bakes produce byte-identical files: nothing in the body depends on the
moment it was generated, only the created: field, which is read back from the file
being replaced and reused, or set to today the first time a catalog is created.

Python 3.9, standard library only, no network.
"""
import argparse
import datetime
import os
import posixpath
import re
import subprocess
import sys

DEFAULT_VAULT = os.environ.get("BROTHERMODE_VAULT") or os.path.expanduser("~/Documents/Kay Vault")

FRONT_TYPE = re.compile(r"^type:\s*(.+)$", re.M)
FRONT_CREATED = re.compile(r"^created:\s*(.+)$", re.M)
FRONT_ID = re.compile(r"^id:\s*(.+?)\s*$", re.M)
FRONT_SYMPTOM = re.compile(r"^symptom:\s*(.+)$", re.M)

UNTYPED_HEADING = "No frontmatter yet"
HERE = os.path.dirname(os.path.abspath(__file__))


def _header_line():
    """The generated-file header. The regeneration command is RESOLVED and
    never hardcoded: a packaged install (pipx, uv, pip) has no tools/
    directory, so a repo-relative path in a shipped string names a file the
    reader does not have. bm_store is loaded BY PATH, the technique the
    sibling tools use so the answer does not depend on the caller's
    sys.path, and lazily, so a caller that never bakes does not pay for it."""
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "bm_store", os.path.join(HERE, "bm_store.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    cmd = mod.invocation("bm-vault-catalog", os.path.abspath(__file__))
    return ("Generated by %s, do not hand edit, regenerate with: %s bake"
            % (os.path.basename(__file__), cmd))


def _vault_root(cli_vault):
    if cli_vault:
        return cli_vault
    env = os.environ.get("BM_VAULT_ROOT")
    if env:
        return env
    return DEFAULT_VAULT


def _relpath(vault_root, abspath):
    return os.path.relpath(abspath, vault_root).replace(os.sep, "/")


def _tracked_md_relpaths(root):
    """.md paths reachable from HEAD under root, relative to root with forward
    slashes, or None when root is not inside a git repository with a resolvable
    HEAD. The catalog describes the COMMITTED repository, not the working
    directory and not the staging index: `git ls-files` would still include a
    file another session has `git add`ed but not yet committed, which is exactly
    the state that produced the 2026-08-28 dangling-link incident, so this reads
    the tree object at HEAD instead."""
    try:
        out = subprocess.run(
            ["git", "-C", root, "ls-tree", "-r", "--name-only", "-z", "HEAD"],
            capture_output=True, check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    # No pathspec: git ls-tree's pathspec matching is not the recursive glob
    # git ls-files gives you, "*.md" against ls-tree silently matches nothing
    # rather than every .md file, so the filter is applied here instead.
    return {p for p in out.stdout.decode("utf-8", "replace").split("\0")
            if p.endswith(".md")}


def _walk_md(root):
    tracked = _tracked_md_relpaths(root)
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if not d.startswith(".")]
        for fn in filenames:
            if not fn.endswith(".md"):
                continue
            abspath = os.path.join(dirpath, fn)
            if tracked is not None and _relpath(root, abspath) not in tracked:
                continue
            yield abspath


def _frontmatter_block(body):
    if not body.startswith("---"):
        return ""
    end = body.find("\n---", 3)
    return body[3:end] if end != -1 else ""


def _date_key(note):
    """created: field if it parses as an ISO date, else the file's own mtime, both
    reduced to a plain YYYY-MM-DD string so the two are comparable."""
    m = FRONT_CREATED.search(_frontmatter_block(note["body"]))
    if m:
        v = m.group(1).strip()
        if re.match(r"^\d{4}-\d{2}-\d{2}", v):
            return v[:10]
    try:
        return datetime.date.fromtimestamp(note["mtime"]).isoformat()
    except (OverflowError, OSError, ValueError):
        return "0000-00-00"


def _read_note(vault_root, abspath):
    """Explicit failure path: an unreadable file is skipped and warned about, never
    silently dropped and never a crash."""
    relpath = _relpath(vault_root, abspath)
    try:
        with open(abspath, encoding="utf-8", errors="replace") as f:
            body = f.read()
    except (IOError, OSError) as e:
        sys.stderr.write("bm_vault_catalog: cannot read %s: %s\n" % (relpath, e))
        return None
    try:
        mtime = os.path.getmtime(abspath)
    except OSError:
        mtime = 0.0
    stem = relpath[:-3] if relpath.lower().endswith(".md") else relpath
    note = {"relpath": relpath, "stem": stem, "body": body, "mtime": mtime}
    note["_date_key"] = _date_key(note)
    return note


def _project_slugs(vault_root):
    root = os.path.join(vault_root, "10-Projects")
    if not os.path.isdir(root):
        return []
    return sorted(d for d in os.listdir(root)
                  if not d.startswith(".") and os.path.isdir(os.path.join(root, d)))


def _project_notes(vault_root, slug):
    root = os.path.join(vault_root, "10-Projects", slug)
    catalog_abs = os.path.abspath(os.path.join(root, "Catalog.md"))
    notes = []
    for abspath in _walk_md(root):
        if os.path.abspath(abspath) == catalog_abs:
            continue
        n = _read_note(vault_root, abspath)
        if n is not None:
            notes.append(n)
    return notes


def _failure_notes(vault_root):
    """Notes eligible for Failures-by-Symptom.md: type: failure AND a symptom: field.
    A note carrying symptom: under any other (or missing) type is never silently
    included or dropped, its relpath comes back in the second list so the caller can
    warn about it."""
    root = os.path.join(vault_root, "40-Failures")
    if not os.path.isdir(root):
        return [], []
    catalog_abs = os.path.abspath(os.path.join(root, "Failures-by-Symptom.md"))
    notes = []
    off_type = []
    for abspath in _walk_md(root):
        if os.path.abspath(abspath) == catalog_abs:
            continue
        n = _read_note(vault_root, abspath)
        if n is None:
            continue
        block = _frontmatter_block(n["body"])
        m = FRONT_SYMPTOM.search(block)
        if not m:
            continue
        n["symptom"] = m.group(1).strip()
        if _type_group(n) == "failure":
            notes.append(n)
        else:
            off_type.append(n["relpath"])
    return notes, off_type


def _type_group(note):
    m = FRONT_TYPE.search(_frontmatter_block(note["body"]))
    return m.group(1).strip() if m else UNTYPED_HEADING


def _today():
    return datetime.date.today().isoformat()


def _existing_created(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            text = f.read()
    except (IOError, OSError):
        return None
    m = FRONT_CREATED.search(_frontmatter_block(text))
    return m.group(1).strip() if m else None


def _created_for(path):
    return _existing_created(path) or _today()


def _existing_id(path):
    # An id: assigned by bm_vault_ids is IDENTITY, not content: a bake that drops
    # it silently invalidates every stored reference to the catalog, and the id
    # check and the staleness check then oscillate forever (assign adds, bake
    # strips). Read it back from the file being replaced, exactly like created:.
    # The first bake of a new catalog has none, and emits none.
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            text = f.read()
    except (IOError, OSError):
        return None
    m = FRONT_ID.search(_frontmatter_block(text))
    return m.group(1).strip() if m else None


def _frontmatter(created, description, note_id=None):
    id_line = ("id: %s\n" % note_id) if note_id else ""
    return (
        "---\n"
        + id_line +
        "type: index\n"
        "status: standing\n"
        "created: %s\n"
        "description: %s\n"
        "tags: [catalog, generated]\n"
        "---\n\n"
    ) % (created, description)


def _sorted_newest_first(notes):
    # Stable double sort: path ascending first, then date descending, so ties on date
    # keep path-ascending order.
    by_path = sorted(notes, key=lambda n: n["relpath"])
    return sorted(by_path, key=lambda n: n["_date_key"], reverse=True)


def _render_project_catalog(slug, notes, created, note_id=None, vault=None):
    groups = {}
    for n in notes:
        groups.setdefault(_type_group(n), []).append(n)
    for key in groups:
        groups[key] = _sorted_newest_first(groups[key])
    lines = [_header_line(), "", "# Catalog: %s" % slug]
    for key in sorted(groups, key=str.casefold):
        lines.append("")
        lines.append("## %s" % key)
        for n in groups[key]:
            alias = posixpath.basename(n["stem"])
            suffix = _alias_suffix(vault, n) if vault else ""
            lines.append("- [[%s|%s]]%s" % (n["stem"], alias, suffix))
    body = "\n".join(lines) + "\n"
    description = "Generated index of every note under 10-Projects/%s/." % slug
    return _frontmatter(created, description, note_id) + body


def _render_failures_by_symptom(notes, created, note_id=None):
    ordered = sorted(notes, key=lambda n: (n["symptom"].casefold(), n["relpath"]))
    lines = [_header_line(), "", "# Failures by symptom", ""]
    for n in ordered:
        alias = posixpath.basename(n["stem"])
        lines.append("- [[%s|%s]]: %s" % (n["stem"], alias, n["symptom"]))
    body = "\n".join(lines) + "\n"
    description = ("Generated flat index, sorted alphabetically by symptom text, of "
                    "every type: failure note carrying a symptom field.")
    return _frontmatter(created, description, note_id) + body


def _write(path, text):
    d = os.path.dirname(path)
    if d:
        os.makedirs(d, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def _is_stale(path, fresh_text):
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            disk = f.read()
    except (IOError, OSError):
        return True
    return disk != fresh_text


def _split_template_dirs(all_slugs):
    """Project directories whose name starts with _ are templates, never baked."""
    skipped = [s for s in all_slugs if s.startswith("_")]
    slugs = [s for s in all_slugs if not s.startswith("_")]
    return slugs, skipped


# ---------------------------------------------------------------------------
# THE VAULT WRITER LOCK, read from tools/bm_vault_lock.py rather than kept here.
#
# An earlier version of this file carried its OWN exclusive lock, at a different
# path, in a different format, with a different stale window. Two lock files that
# cannot see each other are worse than either alone: each session takes the one it
# knows about, both believe they hold the vault, and the protection reports success
# while protecting nothing. So there is one lock in this estate and this file is a
# READER of it.
#
# What is kept from the exclusive design is the REFUSAL, and only here. The lock
# itself is advisory by its author's deliberate choice, and the pre-commit hook
# only warns, because a hard block at commit time has a blast radius far larger
# than the act it guards: the danger is sweeping ANOTHER session's staged files
# into your commit, not committing at all, and a session committing its own work
# with an explicit pathspec is safe. A bake is different. It REPLACES generated
# files wholesale, its blast radius is exactly the bake, and two bakes racing is
# last-write-wins on files neither session knows the other is touching. So a bake
# refuses while another session is active, and nothing else in this estate does.
# ---------------------------------------------------------------------------


def _load_vault_lock():
    """Loaded BY PATH, the technique the sibling tools use, so the answer does not
    depend on whatever sys.path the caller happened to have."""
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "bm_vault_lock", os.path.join(HERE, "bm_vault_lock.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# VB11-03: promoted alias/question-form metadata joins the retrieval index AT
# BAKE, read through the enrichment lane's own promotions-filtered reader,
# never re-decided here. Loaded BY PATH like _load_vault_lock above, and
# guarded the same way every sibling contract loader in this file already is:
# an absent module degrades to "no alias suffixes this bake", stated on
# stderr, never a crash that would take the whole bake down over one
# unrelated file.
def _load_enrich_index():
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "bm_vault_enrich_index", os.path.join(HERE, "bm_vault_enrich_index.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _alias_suffix(vault, note):
    try:
        eix = _load_enrich_index()
    except Exception as exc:
        sys.stderr.write(
            "bm_vault_catalog: could not load bm_vault_enrich_index (%s), so no promoted "
            "alias/question-form metadata was checked for this bake.\n" % exc)
        return ""
    return eix.catalog_line_suffix(vault, note["relpath"])


def _foreign_active_holder(vault):
    """(holder, age_seconds) when ANOTHER session holds a live lock, else None.

    Returns None for our own lock, for a stale one, and for no lock at all. A lock
    file that cannot be read is treated as no lock, which is bm_vault_lock's own
    documented behaviour and is deliberately NOT overridden here: this reader must
    not invent a stricter rule than the lock it reads, or the two disagree."""
    try:
        lk = _load_vault_lock()
    except Exception as exc:
        # SPOKEN, not swallowed. If the lock module cannot be loaded then no lock is
        # consulted and a concurrent bake is not prevented, and this estate's rule is
        # that a tool never reports a protection it did not apply.
        sys.stderr.write(
            "bm_vault_catalog: NO-LOCK, could not load bm_vault_lock (%s), so a "
            "concurrent writer was not checked for.\n" % exc)
        return None
    data = lk._read_lock(lk._lock_path(vault))
    if not data:
        return None
    holder = data.get("session", "unknown")
    if holder == _session_label():
        return None
    try:
        age = (lk.datetime.now(lk.timezone.utc)
               - lk._parse_iso(data.get("acquired", ""))).total_seconds()
    except (ValueError, TypeError) as exc:
        # Said out loud rather than dropped. bm_vault_lock's own check reports an
        # unparseable timestamp as STALE; this reader does not enforce on it, and the
        # difference between "no lock" and "a lock I could not date" is exactly the
        # kind of thing that must not vanish.
        sys.stderr.write(
            "bm_vault_catalog: a vault writer lock exists but its timestamp could not "
            "be read (%s), so it was NOT enforced against this bake.\n" % exc)
        return None
    if age > lk.STALE_SECONDS:
        return None
    return holder, age


def _session_label():
    """Who this process is. Matches bm_vault_lock's own --session convention."""
    return os.environ.get("CLAUDE_SESSION_ID") or ("pid-%d" % os.getpid())


def cmd_bake(args):
    vault = _vault_root(args.vault)
    foreign = _foreign_active_holder(vault)
    if foreign:
        holder, age = foreign
        sys.stderr.write(
            "bm_vault_catalog: refusing to bake. The vault writer lock is held by %s "
            "(%d seconds). A bake replaces generated files wholesale, so racing another "
            "writer is last-write-wins on files neither of you knows the other is "
            "touching. Wait for it, or check whether that session is still alive.\n"
            % (holder, int(age)))
        return 75
    return _bake(vault)


def _bake(vault):
    slugs, skipped = _split_template_dirs(_project_slugs(vault))
    for s in skipped:
        print("skipped template project: 10-Projects/%s" % s)
    for slug in slugs:
        path = os.path.join(vault, "10-Projects", slug, "Catalog.md")
        notes = _project_notes(vault, slug)
        text = _render_project_catalog(slug, notes, _created_for(path), _existing_id(path), vault)
        _write(path, text)
    fpath = os.path.join(vault, "40-Failures", "Failures-by-Symptom.md")
    fnotes, foff_type = _failure_notes(vault)
    for relpath in sorted(foff_type):
        print("warning: %s carries symptom: without type: failure, excluded from "
              "Failures-by-Symptom.md" % relpath)
    ftext = _render_failures_by_symptom(fnotes, _created_for(fpath), _existing_id(fpath))
    _write(fpath, ftext)
    print("baked %d project catalog(s) and Failures-by-Symptom.md (%d failure note(s) "
          "with symptom)" % (len(slugs), len(fnotes)))
    return 0


def cmd_check(args):
    vault = _vault_root(args.vault)
    slugs, _skipped = _split_template_dirs(_project_slugs(vault))
    if not slugs:
        print("NO-DATA: no project directories found under %s/10-Projects" % vault)
        return 3
    stale = []
    for slug in slugs:
        path = os.path.join(vault, "10-Projects", slug, "Catalog.md")
        notes = _project_notes(vault, slug)
        fresh = _render_project_catalog(slug, notes, _created_for(path), _existing_id(path), vault)
        if _is_stale(path, fresh):
            stale.append(_relpath(vault, path))
    fpath = os.path.join(vault, "40-Failures", "Failures-by-Symptom.md")
    fnotes, _foff_type = _failure_notes(vault)
    ffresh = _render_failures_by_symptom(fnotes, _created_for(fpath), _existing_id(fpath))
    if _is_stale(fpath, ffresh):
        stale.append(_relpath(vault, fpath))
    if stale:
        for s in stale:
            print("stale: %s" % s)
        print("%d stale file(s)" % len(stale))
        return 2
    print("OK: %d project catalog(s) plus Failures-by-Symptom.md current" % len(slugs))
    return 0


def _build_parser():
    p = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    pb = sub.add_parser("bake", help="(re)write every generated catalog note")
    pb.add_argument("--vault", default=None)
    pc = sub.add_parser("check", help="exit non-zero when a baked file is stale")
    pc.add_argument("--vault", default=None)
    return p


def main(argv=None):
    args = _build_parser().parse_args(sys.argv[1:] if argv is None else argv)
    if args.cmd == "bake":
        return cmd_bake(args)
    return cmd_check(args)


if __name__ == "__main__":
    sys.exit(main())
